#include "Standalone/TypeDefinitions.h"

void load_type_definitions(mlir::LLVM::LLVMDialect* d) {
    using t = T::t;
    using namespace mlir;

    T::voidTy = t::getVoidTy(d);

    T::Sqlite3ConfigTy = t::createStructTy(d, Optional<StringRef>("Sqlite3Config"));
    T::sqlite3_mem_methodsTy = t::createStructTy(d, Optional<StringRef>("sqlite3_mem_methods"));
    T::sqlite3_mutex_methodsTy = t::createStructTy(d, Optional<StringRef>("sqlite3_mutex_methods"));
    T::sqlite3_pcache_methods2Ty = t::createStructTy(d, Optional<StringRef>("sqlite3_pcache_methods2"));
    T::sqlite3_pcache_pageTy = t::createStructTy(d, Optional<StringRef>("sqlite3_pcache_page"));
    T::DbTy = t::createStructTy(d, Optional<StringRef>("Db"));
    T::sqlite3_valueTy = t::createStructTy(d, Optional<StringRef>("sqlite3_value"));
    T::MemValueTy = t::createStructTy(d, Optional<StringRef>("MemValue"));
    T::sqlite3Ty = t::createStructTy(d, Optional<StringRef>("sqlite3"));
    T::sqlite3_vfsTy = t::createStructTy(d, Optional<StringRef>("sqlite3_vfs"));
    T::sqlite3_fileTy = t::createStructTy(d, Optional<StringRef>("sqlite3_file"));
    T::sqlite3_io_methodsTy = t::createStructTy(d, Optional<StringRef>("sqlite3_io_methods"));
    T::VdbeTy = t::createStructTy(d, Optional<StringRef>("Vdbe"));
    T::VdbeCursorTy = t::createStructTy(d, Optional<StringRef>("VdbeCursor"));
    T::anon7Ty = t::createStructTy(d, Optional<StringRef>("anon7"));
    T::KeyInfoTy = t::createStructTy(d, Optional<StringRef>("KeyInfo"));
    T::VdbeOpTy = t::createStructTy(d, Optional<StringRef>("VdbeOp"));
    T::p4unionTy = t::createStructTy(d, Optional<StringRef>("p4union"));
    T::VdbeFrameTy = t::createStructTy(d, Optional<StringRef>("VdbeFrame"));
    T::SubProgramTy = t::createStructTy(d, Optional<StringRef>("SubProgram"));
    T::AuxDataTy = t::createStructTy(d, Optional<StringRef>("AuxData"));
    T::CollSeqTy = t::createStructTy(d, Optional<StringRef>("CollSeq"));
    T::SchemaTy = t::createStructTy(d, Optional<StringRef>("Schema"));
    T::TableTy = t::createStructTy(d, Optional<StringRef>("Table"));
    T::ColumnTy = t::createStructTy(d, Optional<StringRef>("Column"));
    T::ExprTy = t::createStructTy(d, Optional<StringRef>("Expr"));
    T::anonTy = t::createStructTy(d, Optional<StringRef>("anon"));
    T::anon0Ty = t::createStructTy(d, Optional<StringRef>("anon0"));
    T::AggInfoTy = t::createStructTy(d, Optional<StringRef>("AggInfo"));
    T::AggInfo_colTy = t::createStructTy(d, Optional<StringRef>("AggInfo_col"));
    T::AggInfo_funcTy = t::createStructTy(d, Optional<StringRef>("AggInfo_func"));
    T::FuncDefTy = t::createStructTy(d, Optional<StringRef>("FuncDef"));
    T::sqlite3_contextTy = t::createStructTy(d, Optional<StringRef>("sqlite3_context"));
    T::anon8Ty = t::createStructTy(d, Optional<StringRef>("anon8"));
    T::anon4Ty = t::createStructTy(d, Optional<StringRef>("anon4"));
    T::IndexTy = t::createStructTy(d, Optional<StringRef>("Index"));
    T::SelectTy = t::createStructTy(d, Optional<StringRef>("Select"));
    T::SrcList_itemTy = t::createStructTy(d, Optional<StringRef>("SrcList_item"));
    T::SrcListTy = t::createStructTy(d, Optional<StringRef>("SrcList"));
    T::anon2Ty = t::createStructTy(d, Optional<StringRef>("anon2"));
    T::IdListTy = t::createStructTy(d, Optional<StringRef>("IdList"));
    T::IdList_itemTy = t::createStructTy(d, Optional<StringRef>("IdList_item"));
    T::anon3Ty = t::createStructTy(d, Optional<StringRef>("anon3"));
    T::CteTy = t::createStructTy(d, Optional<StringRef>("Cte"));
    T::WithTy = t::createStructTy(d, Optional<StringRef>("With"));
    T::WindowTy = t::createStructTy(d, Optional<StringRef>("Window"));
    T::sColMapTy = t::createStructTy(d, Optional<StringRef>("sColMap"));
    T::FKeyTy = t::createStructTy(d, Optional<StringRef>("FKey"));
    T::ExprList_itemTy = t::createStructTy(d, Optional<StringRef>("ExprList_item"));
    T::ExprListTy = t::createStructTy(d, Optional<StringRef>("ExprList"));
    T::anon1Ty = t::createStructTy(d, Optional<StringRef>("anon1"));
    T::TriggerTy = t::createStructTy(d, Optional<StringRef>("Trigger"));
    T::TriggerStepTy = t::createStructTy(d, Optional<StringRef>("TriggerStep"));
    T::UpsertTy = t::createStructTy(d, Optional<StringRef>("Upsert"));
    T::sqlite3InitInfoTy = t::createStructTy(d, Optional<StringRef>("sqlite3InitInfo"));
    T::ParseTy = t::createStructTy(d, Optional<StringRef>("Parse"));
    T::AutoincInfoTy = t::createStructTy(d, Optional<StringRef>("AutoincInfo"));
    T::TokenTy = t::createStructTy(d, Optional<StringRef>("Token"));
    T::TriggerPrgTy = t::createStructTy(d, Optional<StringRef>("TriggerPrg"));
    T::anon6Ty = t::createStructTy(d, Optional<StringRef>("anon6"));
    T::LookasideTy = t::createStructTy(d, Optional<StringRef>("Lookaside"));
    T::LookasideSlotTy = t::createStructTy(d, Optional<StringRef>("LookasideSlot"));
    T::VTableTy = t::createStructTy(d, Optional<StringRef>("VTable"));
    T::ModuleTy = t::createStructTy(d, Optional<StringRef>("Module"));
    T::sqlite3_moduleTy = t::createStructTy(d, Optional<StringRef>("sqlite3_module"));
    T::sqlite3_index_infoTy = t::createStructTy(d, Optional<StringRef>("sqlite3_index_info"));
    T::sqlite3_index_constraintTy = t::createStructTy(d, Optional<StringRef>("sqlite3_index_constraint"));
    T::sqlite3_index_orderbyTy = t::createStructTy(d, Optional<StringRef>("sqlite3_index_orderby"));
    T::sqlite3_index_constraint_usageTy = t::createStructTy(d, Optional<StringRef>("sqlite3_index_constraint_usage"));
    T::sqlite3_vtab_cursorTy = t::createStructTy(d, Optional<StringRef>("sqlite3_vtab_cursor"));
    T::sqlite3_vtabTy = t::createStructTy(d, Optional<StringRef>("sqlite3_vtab"));
    T::HashTy = t::createStructTy(d, Optional<StringRef>("Hash"));
    T::HashElemTy = t::createStructTy(d, Optional<StringRef>("HashElem"));
    T::_htTy = t::createStructTy(d, Optional<StringRef>("_ht"));
    T::BusyHandlerTy = t::createStructTy(d, Optional<StringRef>("BusyHandler"));
    T::SavepointTy = t::createStructTy(d, Optional<StringRef>("Savepoint"));
    T::UnpackedRecordTy = t::createStructTy(d, Optional<StringRef>("UnpackedRecord"));
    T::BtreePayloadTy = t::createStructTy(d, Optional<StringRef>("BtreePayload"));
    T::InitDataTy = t::createStructTy(d, Optional<StringRef>("InitData"));
    T::i1Ty = t::getIntNTy(d, 1);


    T::SchemaPtrTy = T::SchemaTy.getPointerTo();
    T::ExprPtrTy = T::ExprTy.getPointerTo();
    T::AggInfoPtrTy = T::AggInfoTy.getPointerTo();
    T::sqlite3_modulePtrTy = T::sqlite3_moduleTy.getPointerTo();
    T::Arr_2_DbTy = t::getArrayTy(T::DbTy, 2);
    T::AuxDataPtrTy = T::AuxDataTy.getPointerTo();
    T::sqlite3_vfsPtrTy = T::sqlite3_vfsTy.getPointerTo();
    T::sqlite3_vtabPtrTy = T::sqlite3_vtabTy.getPointerTo();
    T::CollSeqPtrTy = T::CollSeqTy.getPointerTo();
    T::sqlite3_pcache_pagePtrTy = T::sqlite3_pcache_pageTy.getPointerTo();
    T::LookasideSlotPtrTy = T::LookasideSlotTy.getPointerTo();
    T::BtCursorTy = t::createStructTy(d, Optional<StringRef>("BtCursor"));
    T::sqlite3_valuePtrTy = T::sqlite3_valueTy.getPointerTo();
    T::sqlite3_vtab_cursorPtrTy = T::sqlite3_vtab_cursorTy.getPointerTo();
    T::IndexPtrTy = T::IndexTy.getPointerTo();
    T::IdList_itemPtrTy = T::IdList_itemTy.getPointerTo();
    T::ModulePtrTy = T::ModuleTy.getPointerTo();
    T::sqlite3_index_orderbyPtrTy = T::sqlite3_index_orderbyTy.getPointerTo();
    T::Arr_1_SrcList_itemTy = t::getArrayTy(T::SrcList_itemTy, 1);
    T::Arr_1_ExprList_itemTy = t::getArrayTy(T::ExprList_itemTy, 1);
    T::TablePtrTy = T::TableTy.getPointerTo();
    T::UpsertPtrTy = T::UpsertTy.getPointerTo();
    T::VdbeCursorPtrTy = T::VdbeCursorTy.getPointerTo();
    T::SelectPtrTy = T::SelectTy.getPointerTo();
    T::SubProgramPtrTy = T::SubProgramTy.getPointerTo();
    T::sqlite3_index_infoPtrTy = T::sqlite3_index_infoTy.getPointerTo();
    T::sqlite3_pcacheTy = t::createStructTy(d, Optional<StringRef>("sqlite3_pcache"));
    T::PagerTy = t::createStructTy(d, Optional<StringRef>("Pager"));
    T::SrcListPtrTy = T::SrcListTy.getPointerTo();
    T::Arr_1_sColMapTy = t::getArrayTy(T::sColMapTy, 1);
    T::Arr_1_CteTy = t::getArrayTy(T::CteTy, 1);
    T::VdbePtrTy = T::VdbeTy.getPointerTo();
    T::sqlite3_mutexTy = t::createStructTy(d, Optional<StringRef>("sqlite3_mutex"));
    T::i64Ty = t::getIntNTy(d, 64);
    T::sqlite3_io_methodsPtrTy = T::sqlite3_io_methodsTy.getPointerTo();
    T::BtreeTy = t::createStructTy(d, Optional<StringRef>("Btree"));
    T::RowSetTy = t::createStructTy(d, Optional<StringRef>("RowSet"));
    T::TriggerPtrTy = T::TriggerTy.getPointerTo();
    T::SavepointPtrTy = T::SavepointTy.getPointerTo();
    T::IdListPtrTy = T::IdListTy.getPointerTo();
    T::TriggerStepPtrTy = T::TriggerStepTy.getPointerTo();
    T::_htPtrTy = T::_htTy.getPointerTo();
    T::sqlite3_filePtrTy = T::sqlite3_fileTy.getPointerTo();
    T::VTablePtrTy = T::VTableTy.getPointerTo();
    T::KeyInfoPtrTy = T::KeyInfoTy.getPointerTo();
    T::VoidTy = t::getVoidTy(d);
    T::sqlite3_index_constraintPtrTy = T::sqlite3_index_constraintTy.getPointerTo();
    T::TriggerPrgPtrTy = T::TriggerPrgTy.getPointerTo();
    T::VdbeFramePtrTy = T::VdbeFrameTy.getPointerTo();
    T::VdbeOpPtrTy = T::VdbeOpTy.getPointerTo();
    T::p4unionPtrTy = T::p4unionTy.getPointerTo();
    T::AutoincInfoPtrTy = T::AutoincInfoTy.getPointerTo();
    T::TableLockTy = t::createStructTy(d, Optional<StringRef>("TableLock"));
    T::FuncDefPtrTy = T::FuncDefTy.getPointerTo();
    T::RenameTokenTy = t::createStructTy(d, Optional<StringRef>("RenameToken"));
    T::i32Ty = t::getIntNTy(d, 32);
    T::sqlite3PtrTy = T::sqlite3Ty.getPointerTo();
    T::i8Ty = t::getIntNTy(d, 8);
    T::VtabCtxTy = t::createStructTy(d, Optional<StringRef>("VtabCtx"));
    T::ParsePtrTy = T::ParseTy.getPointerTo();
    T::sqlite3_contextPtrTy = T::sqlite3_contextTy.getPointerTo();
    T::ColumnPtrTy = T::ColumnTy.getPointerTo();
    T::FKeyPtrTy = T::FKeyTy.getPointerTo();
    T::DbPtrTy = T::DbTy.getPointerTo();
    T::WindowPtrTy = T::WindowTy.getPointerTo();
    T::i16Ty = t::getIntNTy(d, 16);
    T::sqlite3_index_constraint_usagePtrTy = T::sqlite3_index_constraint_usageTy.getPointerTo();
    T::HashElemPtrTy = T::HashElemTy.getPointerTo();
    T::WithPtrTy = T::WithTy.getPointerTo();
    T::AggInfo_colPtrTy = T::AggInfo_colTy.getPointerTo();
    T::VdbeSorterTy = t::createStructTy(d, Optional<StringRef>("VdbeSorter"));
    T::AggInfo_funcPtrTy = T::AggInfo_funcTy.getPointerTo();
    T::doubleTy = t::getDoubleTy(d);
    T::ExprListPtrTy = T::ExprListTy.getPointerTo();
    T::Arr_1_sqlite3_valuePtrTy = t::getArrayTy(T::sqlite3_valueTy.getPointerTo(), 1);
    T::i32_Of_sqlite3_vtab_cursorPtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vtab_cursorPtrTy}, false);
    T::Void_Of_VoidTy = t::getFunctionTy(t::getVoidTy(d), {}, false);
    T::i64PtrTy = T::i64Ty.getPointerTo();
    T::Arr_3_i32Ty = t::getArrayTy(t::getIntNTy(d, 32), 3);
    T::Arr_1_i32Ty = t::getArrayTy(t::getIntNTy(d, 32), 1);
    T::Arr_2_TriggerPtrTy = t::getArrayTy(T::TriggerTy.getPointerTo(), 2);
    T::Arr_7_i32Ty = t::getArrayTy(t::getIntNTy(d, 32), 7);
    T::Arr_8_i32Ty = t::getArrayTy(t::getIntNTy(d, 32), 8);
    T::RenameTokenPtrTy = T::RenameTokenTy.getPointerTo();
    T::Void_Of_sqlite3_contextPtrTy = t::getFunctionTy(t::getVoidTy(d), {T::sqlite3_contextPtrTy}, false);
    T::BtreePtrTy = T::BtreeTy.getPointerTo();
    T::i32PtrTy = T::i32Ty.getPointerTo();
    T::i32_Of_sqlite3_filePtr_i32Ty = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_filePtrTy, T::i32Ty}, false);
    T::TablePtrPtrTy = T::TablePtrTy.getPointerTo();
    T::i32_Of_VoidTy = t::getFunctionTy(t::getIntNTy(d, 32), {}, false);
    T::sqlite3_pcachePtrTy = T::sqlite3_pcacheTy.getPointerTo();
    T::sqlite3_vtab_cursorPtrPtrTy = T::sqlite3_vtab_cursorPtrTy.getPointerTo();
    T::i8PtrTy = T::i8Ty.getPointerTo();
    T::sqlite3_vtabPtrPtrTy = T::sqlite3_vtabPtrTy.getPointerTo();
    T::VtabCtxPtrTy = T::VtabCtxTy.getPointerTo();
    T::i32_Of_sqlite3_vfsPtr_i32Ty = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vfsPtrTy, T::i32Ty}, false);
    T::i32_Of_sqlite3_filePtr_i64Ty = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_filePtrTy, T::i64Ty}, false);
    T::i32_Of_sqlite3_vtabPtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vtabPtrTy}, false);
    T::i32_Of_sqlite3_vtabPtr_i32Ty = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vtabPtrTy, T::i32Ty}, false);
    T::TableLockPtrTy = T::TableLockTy.getPointerTo();
    T::i16PtrTy = T::i16Ty.getPointerTo();
    T::Void_Of_sqlite3_filePtrTy = t::getFunctionTy(t::getVoidTy(d), {T::sqlite3_filePtrTy}, false);
    T::WindowPtrPtrTy = T::WindowPtrTy.getPointerTo();
    T::VdbeCursorPtrPtrTy = T::VdbeCursorPtrTy.getPointerTo();
    T::Arr_1_CollSeqPtrTy = t::getArrayTy(T::CollSeqTy.getPointerTo(), 1);
    T::Arr_12_i32Ty = t::getArrayTy(t::getIntNTy(d, 32), 12);
    T::Arr_2_i8Ty = t::getArrayTy(t::getIntNTy(d, 8), 2);
    T::i32_Of_sqlite3_vtab_cursorPtr_sqlite3_contextPtr_i32Ty = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vtab_cursorPtrTy, T::sqlite3_contextPtrTy, T::i32Ty}, false);
    T::i32_Of_sqlite3_vtabPtr_sqlite3_index_infoPtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vtabPtrTy, T::sqlite3_index_infoPtrTy}, false);
    T::i32_Of_i32Ty = t::getFunctionTy(t::getIntNTy(d, 32), {T::i32Ty}, false);
    T::sqlite3_mutexPtrTy = T::sqlite3_mutexTy.getPointerTo();
    T::Arr_4_i8Ty = t::getArrayTy(t::getIntNTy(d, 8), 4);
    T::i32_Of_sqlite3_filePtr_i32_i32_i32Ty = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_filePtrTy, T::i32Ty, T::i32Ty, T::i32Ty}, false);
    T::BtCursorPtrTy = T::BtCursorTy.getPointerTo();
    T::doublePtrTy = T::doubleTy.getPointerTo();
    T::sqlite3_valuePtrPtrTy = T::sqlite3_valuePtrTy.getPointerTo();
    T::Arr_2_i32Ty = t::getArrayTy(t::getIntNTy(d, 32), 2);
    T::VTablePtrPtrTy = T::VTablePtrTy.getPointerTo();
    T::i32_Of_sqlite3_filePtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_filePtrTy}, false);
    T::Arr_3_i8Ty = t::getArrayTy(t::getIntNTy(d, 8), 3);
    T::i32_Of_sqlite3_vtabPtrPtrTy = T::i32_Of_sqlite3_vtabPtrTy.getPointerTo();
    T::i8PtrPtrTy = T::i8PtrTy.getPointerTo();
    T::Void_Of_Void_Of_Sqlite3_Vfs_i8Ptr_i8PtrTy = t::getFunctionTy(t::getFunctionTy(t::getVoidTy(d), {}, false).getPointerTo(), { T::sqlite3_vfsPtrTy, T::i8PtrTy, T::i8PtrTy }, false).getPointerTo();;
    T::i32_Of_sqlite3_vtab_cursorPtr_i64PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vtab_cursorPtrTy, T::i64PtrTy}, false);
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32Ty = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vfsPtrTy, T::i8PtrTy, T::i32Ty}, false);
    T::i32_Of_sqlite3_vtab_cursorPtr_i32_i8Ptr_i32_sqlite3_valuePtrPtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vtab_cursorPtrTy, T::i32Ty, T::i8PtrTy, T::i32Ty, T::sqlite3_valuePtrPtrTy}, false);
    T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32_i32Ty = t::getFunctionTy(t::getVoidTy(d), {T::sqlite3_pcachePtrTy, T::sqlite3_pcache_pagePtrTy, T::i32Ty, T::i32Ty}, false);
    T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32Ty = t::getFunctionTy(t::getVoidTy(d), {T::sqlite3_pcachePtrTy, T::sqlite3_pcache_pagePtrTy, T::i32Ty}, false);
    T::i32_Of_sqlite3_vtabPtr_i32_sqlite3_valuePtrPtr_i64PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vtabPtrTy, T::i32Ty, T::sqlite3_valuePtrPtrTy, T::i64PtrTy}, false);
    T::Void_Of_sqlite3_contextPtrPtrTy = T::Void_Of_sqlite3_contextPtrTy.getPointerTo();
    T::i32_Of_i8PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::i8PtrTy}, false);
    T::i32_Of_sqlite3_vtab_cursorPtr_sqlite3_contextPtr_i32PtrTy = T::i32_Of_sqlite3_vtab_cursorPtr_sqlite3_contextPtr_i32Ty.getPointerTo();
    T::Void_Of_i8PtrTy = t::getFunctionTy(t::getVoidTy(d), {T::i8PtrTy}, false);
    T::i32_Of_sqlite3_filePtr_i8Ptr_i32_i64Ty = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_filePtrTy, T::i8PtrTy, T::i32Ty, T::i64Ty}, false);
    T::i32_Of_sqlite3_vtabPtr_sqlite3_vtab_cursorPtrPtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vtabPtrTy, T::sqlite3_vtab_cursorPtrPtrTy}, false);
    T::i8Ptr_Of_i8Ptr_i32Ty = t::getFunctionTy(T::i8Ty.getPointerTo(), {T::i8PtrTy, T::i32Ty}, false);
    T::sqlite3_mutexPtr_Of_i32Ty = t::getFunctionTy(T::sqlite3_mutexTy.getPointerTo(), {T::i32Ty}, false);
    T::i32_Of_sqlite3_vtabPtr_sqlite3_index_infoPtrPtrTy = T::i32_Of_sqlite3_vtabPtr_sqlite3_index_infoPtrTy.getPointerTo();
    T::sqlite3_pcache_pagePtr_Of_sqlite3_pcachePtr_i32_i32Ty = t::getFunctionTy(T::sqlite3_pcache_pageTy.getPointerTo(), {T::sqlite3_pcachePtrTy, T::i32Ty, T::i32Ty}, false);
    T::i32_Of_sqlite3_pcachePtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_pcachePtrTy}, false);
    T::i32_Of_sqlite3_vfsPtr_i32_i8PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vfsPtrTy, T::i32Ty, T::i8PtrTy}, false);
    T::sqlite3_pcachePtr_Of_i32_i32_i32Ty = t::getFunctionTy(T::sqlite3_pcacheTy.getPointerTo(), {T::i32Ty, T::i32Ty, T::i32Ty}, false);
    T::Void_Of_i8Ptr_i8Ptr_i64Ty = t::getFunctionTy(t::getVoidTy(d), {T::i8PtrTy, T::i8PtrTy, T::i64Ty}, false);
    T::Void_Of_sqlite3_mutexPtrTy = t::getFunctionTy(t::getVoidTy(d), {T::sqlite3_mutexPtrTy}, false);
    T::i32_Of_i8Ptr_sqlite3Ptr_i8Ptr_i32Ty = t::getFunctionTy(t::getIntNTy(d, 32), {T::i8PtrTy, T::sqlite3PtrTy, T::i8PtrTy, T::i32Ty}, false);
    T::i32_Of_sqlite3_filePtr_i64PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_filePtrTy, T::i64PtrTy}, false);
    T::Void_Of_VoidPtrTy = T::Void_Of_VoidTy.getPointerTo();
    T::Void_Of_sqlite3_vfsPtr_i32_i8PtrTy = t::getFunctionTy(t::getVoidTy(d), {T::sqlite3_vfsPtrTy, T::i32Ty, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_filePtr_i32_i32_i32PtrTy = T::i32_Of_sqlite3_filePtr_i32_i32_i32Ty.getPointerTo();
    T::Void_Of_i8Ptr_i32_i8PtrTy = t::getFunctionTy(t::getVoidTy(d), {T::i8PtrTy, T::i32Ty, T::i8PtrTy}, false);
    T::Void_Of_sqlite3_vfsPtr_i8PtrTy = t::getFunctionTy(t::getVoidTy(d), {T::sqlite3_vfsPtrTy, T::i8PtrTy}, false);
    T::i32_Of_i32_i8Ptr_i8Ptr_i8PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::i32Ty, T::i8PtrTy, T::i8PtrTy, T::i8PtrTy}, false);
    T::Void_Of_sqlite3_filePtrPtrTy = T::Void_Of_sqlite3_filePtrTy.getPointerTo();
    T::i32_Of_i32PtrTy = T::i32_Of_i32Ty.getPointerTo();
    T::i32_Of_i8Ptr_i32_i8Ptr_i8Ptr_i8Ptr_i8PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::i8PtrTy, T::i32Ty, T::i8PtrTy, T::i8PtrTy, T::i8PtrTy, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i32PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vfsPtrTy, T::i8PtrTy, T::i32Ty, T::i32PtrTy}, false);
    T::i32_Of_sqlite3_filePtrPtrTy = T::i32_Of_sqlite3_filePtrTy.getPointerTo();
    T::i8Ptr_Of_sqlite3_vfsPtr_i8PtrTy = t::getFunctionTy(T::i8Ty.getPointerTo(), {T::sqlite3_vfsPtrTy, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_vfsPtr_i64PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vfsPtrTy, T::i64PtrTy}, false);
    T::i32_Of_VoidPtrTy = T::i32_Of_VoidTy.getPointerTo();
    T::i32_Of_i8Ptr_i32Ty = t::getFunctionTy(t::getIntNTy(d, 32), {T::i8PtrTy, T::i32Ty}, false);
    T::i32_Of_i8Ptr_i32_i8Ptr_i32_i8PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::i8PtrTy, T::i32Ty, T::i8PtrTy, T::i32Ty, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_filePtr_i32_i8PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_filePtrTy, T::i32Ty, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_mutexPtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_mutexPtrTy}, false);
    T::i32_Of_sqlite3_vtab_cursorPtrPtrTy = T::i32_Of_sqlite3_vtab_cursorPtrTy.getPointerTo();
    T::Void_Of_i8Ptr_i32_i8Ptr_i8Ptr_i64Ty = t::getFunctionTy(t::getVoidTy(d), {T::i8PtrTy, T::i32Ty, T::i8PtrTy, T::i8PtrTy, T::i64Ty}, false);
    T::i32_Of_sqlite3_vtabPtr_i32PtrTy = T::i32_Of_sqlite3_vtabPtr_i32Ty.getPointerTo();
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_sqlite3_filePtr_i32_i32PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vfsPtrTy, T::i8PtrTy, T::sqlite3_filePtrTy, T::i32Ty, T::i32PtrTy}, false);
    T::PxFunctionPtrTy = t::getFunctionTy(T::i8PtrTy, { T::sqlite3_contextPtrTy, T::i32Ty, T::sqlite3_valuePtrTy }, false).getPointerTo();
    T::Void_Of_sqlite3_contextPtr_i32_sqlite3_valuePtrPtrTy = t::getFunctionTy(t::getVoidTy(d), {T::sqlite3_contextPtrTy, T::i32Ty, T::sqlite3_valuePtrPtrTy}, false);
    T::i32_Of_sqlite3_vtabPtr_i8PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vtabPtrTy, T::i8PtrTy}, false);
    T::Void_Of_sqlite3_pcachePtr_i32Ty = t::getFunctionTy(t::getVoidTy(d), {T::sqlite3_pcachePtrTy, T::i32Ty}, false);
    T::Void_Of_i8Ptr_sqlite3Ptr_i32_i8PtrTy = t::getFunctionTy(t::getVoidTy(d), {T::i8PtrTy, T::sqlite3PtrTy, T::i32Ty, T::i8PtrTy}, false);
    T::Void_Of_Void_Of_Sqlite3_Vfs_i8PtrTy = t::getFunctionTy(t::getFunctionTy(t::getVoidTy(d), {}, false).getPointerTo(), { T::sqlite3_vfsPtrTy, T::i8PtrTy }, false).getPointerTo();
    T::i32_Of_sqlite3_filePtr_i64_i8PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_filePtrTy, T::i64Ty, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_vfsPtr_i32PtrTy = T::i32_Of_sqlite3_vfsPtr_i32Ty.getPointerTo();
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i8PtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vfsPtrTy, T::i8PtrTy, T::i32Ty, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_vfsPtr_doublePtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vfsPtrTy, T::doublePtrTy}, false);
    T::Void_Of_sqlite3_pcachePtrTy = t::getFunctionTy(t::getVoidTy(d), {T::sqlite3_pcachePtrTy}, false);
    T::i8Ptr_Of_i32Ty = t::getFunctionTy(T::i8Ty.getPointerTo(), {T::i32Ty}, false);
    T::i32_Of_sqlite3_filePtr_i32PtrTy = T::i32_Of_sqlite3_filePtr_i32Ty.getPointerTo();
    T::Void_Of_sqlite3_contextPtr_i32_sqlite3_valuePtrPtrPtrTy = T::Void_Of_sqlite3_contextPtr_i32_sqlite3_valuePtrPtrTy.getPointerTo();
    T::sqlite3_pcachePtr_Of_i32_i32_i32PtrTy = T::sqlite3_pcachePtr_Of_i32_i32_i32Ty.getPointerTo();
    T::i32_Of_sqlite3_filePtr_i32_i8PtrPtrTy = T::i32_Of_sqlite3_filePtr_i32_i8PtrTy.getPointerTo();
    T::i32_Of_sqlite3_filePtr_i64_i32_i8PtrPtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_filePtrTy, T::i64Ty, T::i32Ty, T::i8PtrPtrTy}, false);
    T::i32_Of_sqlite3_vfsPtr_i32_i8PtrPtrTy = T::i32_Of_sqlite3_vfsPtr_i32_i8PtrTy.getPointerTo();
    T::i32_Of_sqlite3_filePtr_i32_i32_i32_i8PtrPtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_filePtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i8PtrPtrTy}, false);
    T::Void_Of_i8Ptr_sqlite3Ptr_i32_i8PtrPtrTy = T::Void_Of_i8Ptr_sqlite3Ptr_i32_i8PtrTy.getPointerTo();
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_Void_Of_VoidPtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vfsPtrTy, T::i8PtrTy, T::Void_Of_VoidPtrTy}, false);
    T::i32_Of_sqlite3_vtabPtr_i32_sqlite3_valuePtrPtr_i64PtrPtrTy = T::i32_Of_sqlite3_vtabPtr_i32_sqlite3_valuePtrPtr_i64PtrTy.getPointerTo();
    T::i32_Of_sqlite3_vtab_cursorPtr_i32_i8Ptr_i32_sqlite3_valuePtrPtrPtrTy = T::i32_Of_sqlite3_vtab_cursorPtr_i32_i8Ptr_i32_sqlite3_valuePtrPtrTy.getPointerTo();
    T::Void_Of_i8Ptr_i8Ptr_i64PtrTy = T::Void_Of_i8Ptr_i8Ptr_i64Ty.getPointerTo();
    T::i32_Of_sqlite3_pcachePtrPtrTy = T::i32_Of_sqlite3_pcachePtrTy.getPointerTo();
    T::i8Ptr_Of_i32PtrTy = T::i8Ptr_Of_i32Ty.getPointerTo();
    T::Void_Of_i8PtrPtrTy = T::Void_Of_i8PtrTy.getPointerTo();
    T::i32_Of_sqlite3_filePtr_i64PtrPtrTy = T::i32_Of_sqlite3_filePtr_i64PtrTy.getPointerTo();
    T::i32_Of_i8Ptr_i32_i8Ptr_i8Ptr_i8Ptr_i8PtrPtrTy = T::i32_Of_i8Ptr_i32_i8Ptr_i8Ptr_i8Ptr_i8PtrTy.getPointerTo();
    T::i32_Of_sqlite3_filePtr_i32PtrPtrTy = T::i32_Of_sqlite3_filePtr_i32PtrTy.getPointerTo();
    T::i32_Of_sqlite3_vfsPtr_doublePtrPtrTy = T::i32_Of_sqlite3_vfsPtr_doublePtrTy.getPointerTo();
    T::i32_Of_i32_i8Ptr_i8Ptr_i8PtrPtrTy = T::i32_Of_i32_i8Ptr_i8Ptr_i8PtrTy.getPointerTo();
    T::sqlite3_pcache_pagePtr_Of_sqlite3_pcachePtr_i32_i32PtrTy = T::sqlite3_pcache_pagePtr_Of_sqlite3_pcachePtr_i32_i32Ty.getPointerTo();
    T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32_i32PtrTy = T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32_i32Ty.getPointerTo();
    T::i32_Of_sqlite3_vtabPtr_i8PtrPtrTy = T::i32_Of_sqlite3_vtabPtr_i8PtrTy.getPointerTo();
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_sqlite3_filePtr_i32_i32PtrPtrTy = T::i32_Of_sqlite3_vfsPtr_i8Ptr_sqlite3_filePtr_i32_i32PtrTy.getPointerTo();
    T::i8Ptr_Of_i8Ptr_i32PtrTy = T::i8Ptr_Of_i8Ptr_i32Ty.getPointerTo();
    T::Void_Of_sqlite3_pcachePtrPtrTy = T::Void_Of_sqlite3_pcachePtrTy.getPointerTo();
    T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32PtrTy = T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32Ty.getPointerTo();
    T::i8Ptr_Of_sqlite3_vfsPtr_i8PtrPtrTy = T::i8Ptr_Of_sqlite3_vfsPtr_i8PtrTy.getPointerTo();
    T::sqlite3_mutexPtr_Of_i32PtrTy = T::sqlite3_mutexPtr_Of_i32Ty.getPointerTo();
    T::i32_Of_sqlite3_filePtr_i8Ptr_i32_i64PtrTy = T::i32_Of_sqlite3_filePtr_i8Ptr_i32_i64Ty.getPointerTo();
    T::i32_Of_sqlite3_vtabPtr_i32_i8Ptr_PxFunctionPtr_i8PtrPtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3_vtabPtrTy, T::i32Ty, T::i8PtrTy, T::PxFunctionPtrTy, T::i8PtrPtrTy}, false);
    T::Void_Of_sqlite3_vfsPtr_i8PtrPtrTy = T::Void_Of_sqlite3_vfsPtr_i8PtrTy.getPointerTo();
    T::Void_Of_i8Ptr_i32_i8PtrPtrTy = T::Void_Of_i8Ptr_i32_i8PtrTy.getPointerTo();
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i8PtrPtrTy = T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i8PtrTy.getPointerTo();
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i32PtrPtrTy = T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i32PtrTy.getPointerTo();
    T::i32_Of_sqlite3_filePtr_i64_i8PtrPtrTy = T::i32_Of_sqlite3_filePtr_i64_i8PtrTy.getPointerTo();
    T::i32_Of_sqlite3Ptr_i8Ptr_i32_i8PtrPtr_sqlite3_vtabPtrPtr_i8PtrPtrTy = t::getFunctionTy(t::getIntNTy(d, 32), {T::sqlite3PtrTy, T::i8PtrTy, T::i32Ty, T::i8PtrPtrTy, T::sqlite3_vtabPtrPtrTy, T::i8PtrPtrTy}, false);
    T::i32_Of_sqlite3_vtab_cursorPtr_i64PtrPtrTy = T::i32_Of_sqlite3_vtab_cursorPtr_i64PtrTy.getPointerTo();
    T::i32_Of_i8PtrPtrTy = T::i32_Of_i8PtrTy.getPointerTo();
    T::Void_Of_i8Ptr_i32_i8Ptr_i8Ptr_i64PtrTy = T::Void_Of_i8Ptr_i32_i8Ptr_i8Ptr_i64Ty.getPointerTo();
    T::i32_Of_sqlite3_vfsPtr_i64PtrPtrTy = T::i32_Of_sqlite3_vfsPtr_i64PtrTy.getPointerTo();
    T::i32_Of_i8Ptr_sqlite3Ptr_i8Ptr_i32PtrTy = T::i32_Of_i8Ptr_sqlite3Ptr_i8Ptr_i32Ty.getPointerTo();
    T::i32_Of_sqlite3_vtabPtr_sqlite3_vtab_cursorPtrPtrPtrTy = T::i32_Of_sqlite3_vtabPtr_sqlite3_vtab_cursorPtrPtrTy.getPointerTo();
    T::i32_Of_sqlite3_mutexPtrPtrTy = T::i32_Of_sqlite3_mutexPtrTy.getPointerTo();
    T::Void_Of_sqlite3_pcachePtr_i32PtrTy = T::Void_Of_sqlite3_pcachePtr_i32Ty.getPointerTo();
    T::i32_Of_i8Ptr_i32PtrTy = T::i32_Of_i8Ptr_i32Ty.getPointerTo();
    T::Void_Of_sqlite3_vfsPtr_i32_i8PtrPtrTy = T::Void_Of_sqlite3_vfsPtr_i32_i8PtrTy.getPointerTo();
    T::Void_Of_sqlite3_mutexPtrPtrTy = T::Void_Of_sqlite3_mutexPtrTy.getPointerTo();
    T::i32_Of_i8Ptr_i32_i8Ptr_i32_i8PtrPtrTy = T::i32_Of_i8Ptr_i32_i8Ptr_i32_i8PtrTy.getPointerTo();
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32PtrTy = T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32Ty.getPointerTo();
    T::i32_Of_sqlite3_vtabPtr_i32_i8Ptr_PxFunctionPtr_i8PtrPtrPtrTy = T::i32_Of_sqlite3_vtabPtr_i32_i8Ptr_PxFunctionPtr_i8PtrPtrTy.getPointerTo();
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_Void_Of_VoidPtrPtrTy = T::i32_Of_sqlite3_vfsPtr_i8Ptr_Void_Of_VoidPtrTy.getPointerTo();
    T::i32_Of_sqlite3_filePtr_i64_i32_i8PtrPtrPtrTy = T::i32_Of_sqlite3_filePtr_i64_i32_i8PtrPtrTy.getPointerTo();
    T::i32_Of_sqlite3Ptr_i8Ptr_i32_i8PtrPtr_sqlite3_vtabPtrPtr_i8PtrPtrPtrTy = T::i32_Of_sqlite3Ptr_i8Ptr_i32_i8PtrPtr_sqlite3_vtabPtrPtr_i8PtrPtrTy.getPointerTo();
    T::i32_Of_sqlite3_filePtr_i32_i32_i32_i8PtrPtrPtrTy = T::i32_Of_sqlite3_filePtr_i32_i32_i32_i8PtrPtrTy.getPointerTo();
    t::setStructTyBody(T::Sqlite3ConfigTy, { T::i32Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::sqlite3_mem_methodsTy, T::sqlite3_mutex_methodsTy, T::sqlite3_pcache_methods2Ty, T::i8PtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i64Ty, T::i64Ty, T::i8PtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::sqlite3_mutexPtrTy, T::Void_Of_i8Ptr_i32_i8PtrPtrTy, T::i8PtrTy, T::i32_Of_i32PtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty }, false);
    t::setStructTyBody(T::sqlite3_mem_methodsTy, { T::i8Ptr_Of_i32PtrTy, T::Void_Of_i8PtrPtrTy, T::i8Ptr_Of_i8Ptr_i32PtrTy, T::i32_Of_i8PtrPtrTy, T::i32_Of_i32PtrTy, T::i32_Of_i8PtrPtrTy, T::Void_Of_i8PtrPtrTy, T::i8PtrTy }, false);
    t::setStructTyBody(T::sqlite3_mutex_methodsTy, { T::i32_Of_VoidPtrTy, T::i32_Of_VoidPtrTy, T::sqlite3_mutexPtr_Of_i32PtrTy, T::Void_Of_sqlite3_mutexPtrPtrTy, T::Void_Of_sqlite3_mutexPtrPtrTy, T::i32_Of_sqlite3_mutexPtrPtrTy, T::Void_Of_sqlite3_mutexPtrPtrTy, T::i32_Of_sqlite3_mutexPtrPtrTy, T::i32_Of_sqlite3_mutexPtrPtrTy }, false);
    t::setStructTyBody(T::sqlite3_pcache_methods2Ty, { T::i32Ty, T::i8PtrTy, T::i32_Of_i8PtrPtrTy, T::Void_Of_i8PtrPtrTy, T::sqlite3_pcachePtr_Of_i32_i32_i32PtrTy, T::Void_Of_sqlite3_pcachePtr_i32PtrTy, T::i32_Of_sqlite3_pcachePtrPtrTy, T::sqlite3_pcache_pagePtr_Of_sqlite3_pcachePtr_i32_i32PtrTy, T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32PtrTy, T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32_i32PtrTy, T::Void_Of_sqlite3_pcachePtr_i32PtrTy, T::Void_Of_sqlite3_pcachePtrPtrTy, T::Void_Of_sqlite3_pcachePtrPtrTy }, false);
    t::setStructTyBody(T::sqlite3_pcache_pageTy, { T::i8PtrTy, T::i8PtrTy }, false);
    t::setStructTyBody(T::DbTy, { T::i8PtrTy, T::BtreePtrTy, T::i8Ty, T::i8Ty, T::SchemaPtrTy }, false);
    t::setStructTyBody(T::sqlite3_valueTy, { T::MemValueTy, T::i16Ty, T::i8Ty, T::i8Ty, T::i32Ty, T::i8PtrTy, T::i8PtrTy, T::i32Ty, T::i32Ty, T::sqlite3PtrTy, T::Void_Of_i8PtrPtrTy }, false);
    t::setStructTyBody(T::MemValueTy, { T::doubleTy }, false);
    t::setStructTyBody(T::sqlite3Ty, { T::sqlite3_vfsPtrTy, T::VdbePtrTy, T::CollSeqPtrTy, T::sqlite3_mutexPtrTy, T::DbPtrTy, T::i32Ty, T::i32Ty, T::i64Ty, T::i64Ty, T::i64Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i16Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::Arr_12_i32Ty, T::i32Ty, T::sqlite3InitInfoTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i8PtrPtrTy, T::i32_Of_i32_i8Ptr_i8Ptr_i8PtrPtrTy, T::i8PtrTy, T::Void_Of_i8Ptr_i8Ptr_i64PtrTy, T::i8PtrTy, T::i8PtrTy, T::i32_Of_i8PtrPtrTy, T::i8PtrTy, T::Void_Of_i8PtrPtrTy, T::i8PtrTy, T::Void_Of_i8Ptr_i32_i8Ptr_i8Ptr_i64PtrTy, T::ParsePtrTy, T::i32_Of_i8Ptr_sqlite3Ptr_i8Ptr_i32PtrTy, T::i8PtrTy, T::Void_Of_i8Ptr_sqlite3Ptr_i32_i8PtrPtrTy, T::Void_Of_i8Ptr_sqlite3Ptr_i32_i8PtrPtrTy, T::i8PtrTy, T::sqlite3_valuePtrTy, T::anon6Ty, T::LookasideTy, T::i32_Of_i8Ptr_i32_i8Ptr_i8Ptr_i8Ptr_i8PtrPtrTy, T::i8PtrTy, T::i32_Of_i8PtrPtrTy, T::i8PtrTy, T::i32Ty, T::i32Ty, T::HashTy, T::VtabCtxPtrTy, T::VTablePtrPtrTy, T::VTablePtrTy, T::HashTy, T::HashTy, T::BusyHandlerTy, T::Arr_2_DbTy, T::SavepointPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i64Ty, T::i64Ty, T::i32PtrTy }, false);
    t::setStructTyBody(T::sqlite3_vfsTy, { T::i32Ty, T::i32Ty, T::i32Ty, T::sqlite3_vfsPtrTy, T::i8PtrTy, T::i8PtrTy, T::i32_Of_sqlite3_vfsPtr_i8Ptr_sqlite3_filePtr_i32_i32PtrPtrTy, T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32PtrTy, T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i32PtrPtrTy, T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i8PtrPtrTy, T::i8Ptr_Of_sqlite3_vfsPtr_i8PtrPtrTy, T::Void_Of_sqlite3_vfsPtr_i32_i8PtrPtrTy, T::Void_Of_Void_Of_Sqlite3_Vfs_i8Ptr_i8PtrTy, T::Void_Of_sqlite3_vfsPtr_i8PtrPtrTy, T::i32_Of_sqlite3_vfsPtr_i32_i8PtrPtrTy, T::i32_Of_sqlite3_vfsPtr_i32PtrTy, T::i32_Of_sqlite3_vfsPtr_doublePtrPtrTy, T::i32_Of_sqlite3_vfsPtr_i32_i8PtrPtrTy, T::i32_Of_sqlite3_vfsPtr_i64PtrPtrTy, T::i32_Of_sqlite3_vfsPtr_i8Ptr_Void_Of_VoidPtrPtrTy, T::Void_Of_Void_Of_Sqlite3_Vfs_i8PtrTy, T::i8Ptr_Of_sqlite3_vfsPtr_i8PtrPtrTy }, false);
    t::setStructTyBody(T::sqlite3_fileTy, { T::sqlite3_io_methodsPtrTy }, false);
    t::setStructTyBody(T::sqlite3_io_methodsTy, { T::i32Ty, T::i32_Of_sqlite3_filePtrPtrTy, T::i32_Of_sqlite3_filePtr_i8Ptr_i32_i64PtrTy, T::i32_Of_sqlite3_filePtr_i8Ptr_i32_i64PtrTy, T::i32_Of_sqlite3_filePtr_i64PtrTy, T::i32_Of_sqlite3_filePtr_i32PtrTy, T::i32_Of_sqlite3_filePtr_i64PtrPtrTy, T::i32_Of_sqlite3_filePtr_i32PtrTy, T::i32_Of_sqlite3_filePtr_i32PtrTy, T::i32_Of_sqlite3_filePtr_i32PtrPtrTy, T::i32_Of_sqlite3_filePtr_i32_i8PtrPtrTy, T::i32_Of_sqlite3_filePtrPtrTy, T::i32_Of_sqlite3_filePtrPtrTy, T::i32_Of_sqlite3_filePtr_i32_i32_i32_i8PtrPtrPtrTy, T::i32_Of_sqlite3_filePtr_i32_i32_i32PtrTy, T::Void_Of_sqlite3_filePtrPtrTy, T::i32_Of_sqlite3_filePtr_i32PtrTy, T::i32_Of_sqlite3_filePtr_i64_i32_i8PtrPtrPtrTy, T::i32_Of_sqlite3_filePtr_i64_i8PtrPtrTy }, false);
    t::setStructTyBody(T::VdbeTy, { T::sqlite3PtrTy, T::VdbePtrTy, T::VdbePtrTy, T::ParsePtrTy, T::i16Ty, T::Arr_2_i8Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::Arr_4_i8Ty, T::i64Ty, T::i64Ty, T::i64Ty, T::i64Ty, T::sqlite3_valuePtrTy, T::sqlite3_valuePtrPtrTy, T::VdbeCursorPtrPtrTy, T::sqlite3_valuePtrTy, T::VdbeOpPtrTy, T::i32Ty, T::i32Ty, T::sqlite3_valuePtrTy, T::sqlite3_valuePtrTy, T::i8PtrTy, T::i32PtrTy, T::i64Ty, T::i16Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i16Ty, T::i8Ty, T::i32Ty, T::i32Ty, T::Arr_7_i32Ty, T::Arr_4_i8Ty, T::i8PtrTy, T::i8PtrTy, T::VdbeFramePtrTy, T::VdbeFramePtrTy, T::i32Ty, T::i32Ty, T::SubProgramPtrTy, T::AuxDataPtrTy }, true);
    t::setStructTyBody(T::VdbeCursorTy, { T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::BtreePtrTy, T::i64Ty, T::i32PtrTy, T::i32Ty, T::i32Ty, T::VdbeCursorPtrTy, T::anon7Ty, T::KeyInfoPtrTy, T::i32Ty, T::i32Ty, T::i16Ty, T::i16Ty, T::i64Ty, T::i32PtrTy, T::i8PtrTy, T::i32Ty, T::i32Ty, T::Arr_1_i32Ty }, false);
    t::setStructTyBody(T::anon7Ty, { T::BtCursorPtrTy }, false);
    t::setStructTyBody(T::KeyInfoTy, { T::i32Ty, T::i8Ty, T::i16Ty, T::i16Ty, T::sqlite3PtrTy, T::i8PtrTy, T::Arr_1_CollSeqPtrTy }, false);
    t::setStructTyBody(T::VdbeOpTy, { T::i8Ty, T::i8Ty, T::i16Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::p4unionTy }, false);
    t::setStructTyBody(T::p4unionTy, { T::i8PtrTy }, false);
    t::setStructTyBody(T::VdbeFrameTy, { T::VdbePtrTy, T::VdbeFramePtrTy, T::VdbeOpPtrTy, T::i64PtrTy, T::sqlite3_valuePtrTy, T::VdbeCursorPtrPtrTy, T::i8PtrTy, T::i8PtrTy, T::i64Ty, T::AuxDataPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty }, false);
    t::setStructTyBody(T::SubProgramTy, { T::VdbeOpPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i8PtrTy, T::i8PtrTy, T::SubProgramPtrTy }, false);
    t::setStructTyBody(T::AuxDataTy, { T::i32Ty, T::i32Ty, T::i8PtrTy, T::Void_Of_i8PtrPtrTy, T::AuxDataPtrTy }, false);
    t::setStructTyBody(T::CollSeqTy, { T::i8PtrTy, T::i8Ty, T::i8PtrTy, T::i32_Of_i8Ptr_i32_i8Ptr_i32_i8PtrPtrTy, T::Void_Of_i8PtrPtrTy }, false);
    t::setStructTyBody(T::SchemaTy, { T::i32Ty, T::i32Ty, T::HashTy, T::HashTy, T::HashTy, T::HashTy, T::TablePtrTy, T::i8Ty, T::i8Ty, T::i16Ty, T::i32Ty }, false);
    t::setStructTyBody(T::TableTy, { T::i8PtrTy, T::ColumnPtrTy, T::IndexPtrTy, T::SelectPtrTy, T::FKeyPtrTy, T::i8PtrTy, T::ExprListPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i16Ty, T::i16Ty, T::i16Ty, T::i16Ty, T::i16Ty, T::i8Ty, T::i32Ty, T::i32Ty, T::i8PtrPtrTy, T::VTablePtrTy, T::TriggerPtrTy, T::SchemaPtrTy, T::TablePtrTy }, false);
    t::setStructTyBody(T::ColumnTy, { T::i8PtrTy, T::ExprPtrTy, T::i8PtrTy, T::i8Ty, T::i8Ty, T::i8Ty, T::i16Ty }, false);
    t::setStructTyBody(T::ExprTy, { T::i8Ty, T::i8Ty, T::i8Ty, T::i32Ty, T::anonTy, T::ExprPtrTy, T::ExprPtrTy, T::anon0Ty, T::i32Ty, T::i32Ty, T::i16Ty, T::i16Ty, T::i16Ty, T::AggInfoPtrTy, T::anon4Ty }, false);
    t::setStructTyBody(T::anonTy, { T::i8PtrTy }, false);
    t::setStructTyBody(T::anon0Ty, { T::ExprListPtrTy }, false);
    t::setStructTyBody(T::AggInfoTy, { T::i8Ty, T::i8Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::ExprListPtrTy, T::AggInfo_colPtrTy, T::i32Ty, T::i32Ty, T::AggInfo_funcPtrTy, T::i32Ty }, false);
    t::setStructTyBody(T::AggInfo_colTy, { T::TablePtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::ExprPtrTy }, false);
    t::setStructTyBody(T::AggInfo_funcTy, { T::ExprPtrTy, T::FuncDefPtrTy, T::i32Ty, T::i32Ty }, false);
    t::setStructTyBody(T::FuncDefTy, { T::i8Ty, T::i32Ty, T::i8PtrTy, T::FuncDefPtrTy, T::Void_Of_sqlite3_contextPtr_i32_sqlite3_valuePtrPtrPtrTy, T::Void_Of_sqlite3_contextPtrPtrTy, T::Void_Of_sqlite3_contextPtrPtrTy, T::Void_Of_sqlite3_contextPtr_i32_sqlite3_valuePtrPtrPtrTy, T::i8PtrTy, T::anon8Ty }, false);
    t::setStructTyBody(T::sqlite3_contextTy, { T::sqlite3_valuePtrTy, T::FuncDefPtrTy, T::sqlite3_valuePtrTy, T::VdbePtrTy, T::i32Ty, T::i32Ty, T::i8Ty, T::i8Ty, T::Arr_1_sqlite3_valuePtrTy }, false);
    t::setStructTyBody(T::anon8Ty, { T::FuncDefPtrTy }, false);
    t::setStructTyBody(T::anon4Ty, { T::TablePtrTy }, false);
    t::setStructTyBody(T::IndexTy, { T::i8PtrTy, T::i16PtrTy, T::i16PtrTy, T::TablePtrTy, T::i8PtrTy, T::IndexPtrTy, T::SchemaPtrTy, T::i8PtrTy, T::i8PtrPtrTy, T::ExprPtrTy, T::ExprListPtrTy, T::i32Ty, T::i16Ty, T::i16Ty, T::i16Ty, T::i8Ty, T::i16Ty, T::Arr_3_i8Ty, T::i64Ty }, true);
    t::setStructTyBody(T::SelectTy, { T::i8Ty, T::i16Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::Arr_2_i32Ty, T::ExprListPtrTy, T::SrcListPtrTy, T::ExprPtrTy, T::ExprListPtrTy, T::ExprPtrTy, T::ExprListPtrTy, T::SelectPtrTy, T::SelectPtrTy, T::ExprPtrTy, T::WithPtrTy, T::WindowPtrTy, T::WindowPtrTy }, false);
    t::setStructTyBody(T::SrcList_itemTy, { T::SchemaPtrTy, T::i8PtrTy, T::i8PtrTy, T::i8PtrTy, T::TablePtrTy, T::SelectPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::anon2Ty, T::i32Ty, T::ExprPtrTy, T::IdListPtrTy, T::i64Ty, T::anon3Ty, T::IndexPtrTy }, false);
    t::setStructTyBody(T::SrcListTy, { T::i32Ty, T::i32Ty, T::Arr_1_SrcList_itemTy }, false);
    t::setStructTyBody(T::anon2Ty, { T::i8Ty, T::i8Ty, T::Arr_2_i8Ty }, false);
    t::setStructTyBody(T::IdListTy, { T::IdList_itemPtrTy, T::i32Ty }, false);
    t::setStructTyBody(T::IdList_itemTy, { T::i8PtrTy, T::i32Ty }, false);
    t::setStructTyBody(T::anon3Ty, { T::i8PtrTy }, false);
    t::setStructTyBody(T::CteTy, { T::i8PtrTy, T::ExprListPtrTy, T::SelectPtrTy, T::i8PtrTy }, false);
    t::setStructTyBody(T::WithTy, { T::i32Ty, T::WithPtrTy, T::Arr_1_CteTy }, false);
    t::setStructTyBody(T::WindowTy, { T::i8PtrTy, T::i8PtrTy, T::ExprListPtrTy, T::ExprListPtrTy, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::ExprPtrTy, T::ExprPtrTy, T::WindowPtrPtrTy, T::WindowPtrTy, T::ExprPtrTy, T::FuncDefPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::ExprPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i8Ty }, false);
    t::setStructTyBody(T::sColMapTy, { T::i32Ty, T::i8PtrTy }, false);
    t::setStructTyBody(T::FKeyTy, { T::TablePtrTy, T::FKeyPtrTy, T::i8PtrTy, T::FKeyPtrTy, T::FKeyPtrTy, T::i32Ty, T::i8Ty, T::Arr_2_i8Ty, T::Arr_2_TriggerPtrTy, T::Arr_1_sColMapTy }, false);
    t::setStructTyBody(T::ExprList_itemTy, { T::ExprPtrTy, T::i8PtrTy, T::i8Ty, T::i8Ty, T::anon1Ty }, false);
    t::setStructTyBody(T::ExprListTy, { T::i32Ty, T::Arr_1_ExprList_itemTy }, false);
    t::setStructTyBody(T::anon1Ty, { T::i32Ty }, false);
    t::setStructTyBody(T::TriggerTy, { T::i8PtrTy, T::i8PtrTy, T::i8Ty, T::i8Ty, T::ExprPtrTy, T::IdListPtrTy, T::SchemaPtrTy, T::SchemaPtrTy, T::TriggerStepPtrTy, T::TriggerPtrTy }, false);
    t::setStructTyBody(T::TriggerStepTy, { T::i8Ty, T::i8Ty, T::TriggerPtrTy, T::SelectPtrTy, T::i8PtrTy, T::ExprPtrTy, T::ExprListPtrTy, T::IdListPtrTy, T::UpsertPtrTy, T::i8PtrTy, T::TriggerStepPtrTy, T::TriggerStepPtrTy }, false);
    t::setStructTyBody(T::UpsertTy, { T::ExprListPtrTy, T::ExprPtrTy, T::ExprListPtrTy, T::ExprPtrTy, T::IndexPtrTy, T::SrcListPtrTy, T::i32Ty, T::i32Ty, T::i32Ty }, false);
    t::setStructTyBody(T::sqlite3InitInfoTy, { T::i32Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8PtrPtrTy }, false);
    t::setStructTyBody(T::ParseTy, { T::sqlite3PtrTy, T::i8PtrTy, T::VdbePtrTy, T::i32Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32PtrTy, T::ExprListPtrTy, T::TokenTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::TableLockPtrTy, T::AutoincInfoPtrTy, T::ParsePtrTy, T::TablePtrTy, T::ParsePtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::Arr_8_i32Ty, T::TokenTy, T::TokenTy, T::i16Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32PtrTy, T::VdbePtrTy, T::i8PtrTy, T::TablePtrTy, T::IndexPtrTy, T::TriggerPtrTy, T::i8PtrTy, T::TokenTy, T::TablePtrPtrTy, T::TablePtrTy, T::TriggerPrgPtrTy, T::WithPtrTy, T::WithPtrTy, T::RenameTokenPtrTy }, false);
    t::setStructTyBody(T::AutoincInfoTy, { T::AutoincInfoPtrTy, T::TablePtrTy, T::i32Ty, T::i32Ty }, false);
    t::setStructTyBody(T::TokenTy, { T::i8PtrTy, T::i32Ty }, false);
    t::setStructTyBody(T::TriggerPrgTy, { T::TriggerPtrTy, T::TriggerPrgPtrTy, T::SubProgramPtrTy, T::i32Ty, T::Arr_2_i32Ty }, false);
    t::setStructTyBody(T::anon6Ty, { T::doubleTy }, false);
    t::setStructTyBody(T::LookasideTy, { T::i32Ty, T::i16Ty, T::i16Ty, T::i8Ty, T::i32Ty, T::Arr_3_i32Ty, T::LookasideSlotPtrTy, T::LookasideSlotPtrTy, T::LookasideSlotPtrTy, T::LookasideSlotPtrTy, T::i8PtrTy, T::i8PtrTy, T::i8PtrTy }, false);
    t::setStructTyBody(T::LookasideSlotTy, { T::LookasideSlotPtrTy }, false);
    t::setStructTyBody(T::VTableTy, { T::sqlite3PtrTy, T::ModulePtrTy, T::sqlite3_vtabPtrTy, T::i32Ty, T::i8Ty, T::i8Ty, T::i32Ty, T::VTablePtrTy }, false);
    t::setStructTyBody(T::ModuleTy, { T::sqlite3_modulePtrTy, T::i8PtrTy, T::i32Ty, T::i8PtrTy, T::Void_Of_i8PtrPtrTy, T::TablePtrTy }, false);
    t::setStructTyBody(T::sqlite3_moduleTy, { T::i32Ty, T::i32_Of_sqlite3Ptr_i8Ptr_i32_i8PtrPtr_sqlite3_vtabPtrPtr_i8PtrPtrPtrTy, T::i32_Of_sqlite3Ptr_i8Ptr_i32_i8PtrPtr_sqlite3_vtabPtrPtr_i8PtrPtrPtrTy, T::i32_Of_sqlite3_vtabPtr_sqlite3_index_infoPtrPtrTy, T::i32_Of_sqlite3_vtabPtrPtrTy, T::i32_Of_sqlite3_vtabPtrPtrTy, T::i32_Of_sqlite3_vtabPtr_sqlite3_vtab_cursorPtrPtrPtrTy, T::i32_Of_sqlite3_vtab_cursorPtrPtrTy, T::i32_Of_sqlite3_vtab_cursorPtr_i32_i8Ptr_i32_sqlite3_valuePtrPtrPtrTy, T::i32_Of_sqlite3_vtab_cursorPtrPtrTy, T::i32_Of_sqlite3_vtab_cursorPtrPtrTy, T::i32_Of_sqlite3_vtab_cursorPtr_sqlite3_contextPtr_i32PtrTy, T::i32_Of_sqlite3_vtab_cursorPtr_i64PtrPtrTy, T::i32_Of_sqlite3_vtabPtr_i32_sqlite3_valuePtrPtr_i64PtrPtrTy, T::i32_Of_sqlite3_vtabPtrPtrTy, T::i32_Of_sqlite3_vtabPtrPtrTy, T::i32_Of_sqlite3_vtabPtrPtrTy, T::i32_Of_sqlite3_vtabPtrPtrTy, T::i32_Of_sqlite3_vtabPtr_i32_i8Ptr_PxFunctionPtr_i8PtrPtrPtrTy, T::i32_Of_sqlite3_vtabPtr_i8PtrPtrTy, T::i32_Of_sqlite3_vtabPtr_i32PtrTy, T::i32_Of_sqlite3_vtabPtr_i32PtrTy, T::i32_Of_sqlite3_vtabPtr_i32PtrTy, T::i32_Of_i8PtrPtrTy }, false);
    t::setStructTyBody(T::sqlite3_index_infoTy, { T::i32Ty, T::sqlite3_index_constraintPtrTy, T::i32Ty, T::sqlite3_index_orderbyPtrTy, T::sqlite3_index_constraint_usagePtrTy, T::i32Ty, T::i8PtrTy, T::i32Ty, T::i32Ty, T::doubleTy, T::i64Ty, T::i32Ty, T::i64Ty }, false);
    t::setStructTyBody(T::sqlite3_index_constraintTy, { T::i32Ty, T::i8Ty, T::i8Ty, T::i32Ty }, false);
    t::setStructTyBody(T::sqlite3_index_orderbyTy, { T::i32Ty, T::i8Ty }, false);
    t::setStructTyBody(T::sqlite3_index_constraint_usageTy, { T::i32Ty, T::i8Ty }, false);
    t::setStructTyBody(T::sqlite3_vtab_cursorTy, { T::sqlite3_vtabPtrTy }, false);
    t::setStructTyBody(T::sqlite3_vtabTy, { T::sqlite3_modulePtrTy, T::i32Ty, T::i8PtrTy }, false);
    t::setStructTyBody(T::HashTy, { T::i32Ty, T::i32Ty, T::HashElemPtrTy, T::_htPtrTy }, false);
    t::setStructTyBody(T::HashElemTy, { T::HashElemPtrTy, T::HashElemPtrTy, T::i8PtrTy, T::i8PtrTy }, false);
    t::setStructTyBody(T::_htTy, { T::i32Ty, T::HashElemPtrTy }, false);
    t::setStructTyBody(T::BusyHandlerTy, { T::i32_Of_i8Ptr_i32PtrTy, T::i8PtrTy, T::i32Ty, T::i8Ty }, false);
    t::setStructTyBody(T::SavepointTy, { T::i8PtrTy, T::i64Ty, T::i64Ty, T::SavepointPtrTy }, false);
    t::setStructTyBody(T::UnpackedRecordTy, { T::KeyInfoPtrTy, T::sqlite3_valuePtrTy, T::i16Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty }, false);
    t::setStructTyBody(T::BtreePayloadTy, { T::i8PtrTy, T::i64Ty, T::i8PtrTy, T::sqlite3_valuePtrTy, T::i16Ty, T::i32Ty, T::i32Ty }, false);
    t::setStructTyBody(T::InitDataTy, { T::sqlite3PtrTy, T::i8PtrPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty }, false);
}
