BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Sales" (
	"S_ID"	INTEGER NOT NULL UNIQUE,
	"S_Price"	REAL NOT NULL,
	"S_Client"	INTEGER,
	"S_Date"	TEXT NOT NULL,
	PRIMARY KEY("S_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Clients" (
	"C_ID"	INTEGER NOT NULL UNIQUE,
	"C_Name"	TEXT NOT NULL,
	"C_CreatedAt"	INTEGER NOT NULL,
	"C_Address"	TEXT NOT NULL,
	"C_Balance"	REAL NOT NULL,
	PRIMARY KEY("C_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Items" (
	"I_ID"	INTEGER NOT NULL UNIQUE,
	"I_Name"	TEXT NOT NULL,
	"I_Price"	REAL NOT NULL,
	"I_Category"	INTEGER,
	PRIMARY KEY("I_ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "SaleItem" (
	"SI_S"	INTEGER NOT NULL,
	"SI_I"	INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS "Idx_Sales_Clients" ON "Sales" (
	"S_Client"
);
COMMIT;
