#include "type_definitions.h"

void load_type_definitions(my_context& ctx) {
    T::Sqlite3ConfigTy = StructType::create(ctx.context, "Sqlite3Config");
    T::sqlite3_mem_methodsTy = StructType::create(ctx.context, "sqlite3_mem_methods");
    T::sqlite3_mutex_methodsTy = StructType::create(ctx.context, "sqlite3_mutex_methods");
    T::sqlite3_pcache_methods2Ty = StructType::create(ctx.context, "sqlite3_pcache_methods2");
    T::sqlite3_pcache_pageTy = StructType::create(ctx.context, "sqlite3_pcache_page");
    T::DbTy = StructType::create(ctx.context, "Db");
    T::sqlite3_valueTy = StructType::create(ctx.context, "sqlite3_value");
    T::MemValueTy = StructType::create(ctx.context, "MemValue");
    T::sqlite3Ty = StructType::create(ctx.context, "sqlite3");
    T::sqlite3_vfsTy = StructType::create(ctx.context, "sqlite3_vfs");
    T::sqlite3_fileTy = StructType::create(ctx.context, "sqlite3_file");
    T::sqlite3_io_methodsTy = StructType::create(ctx.context, "sqlite3_io_methods");
    T::VdbeTy = StructType::create(ctx.context, "Vdbe");
    T::VdbeCursorTy = StructType::create(ctx.context, "VdbeCursor");
    T::anon7Ty = StructType::create(ctx.context, "anon7");
    T::KeyInfoTy = StructType::create(ctx.context, "KeyInfo");
    T::VdbeOpTy = StructType::create(ctx.context, "VdbeOp");
    T::p4unionTy = StructType::create(ctx.context, "p4union");
    T::VdbeFrameTy = StructType::create(ctx.context, "VdbeFrame");
    T::SubProgramTy = StructType::create(ctx.context, "SubProgram");
    T::AuxDataTy = StructType::create(ctx.context, "AuxData");
    T::CollSeqTy = StructType::create(ctx.context, "CollSeq");
    T::SchemaTy = StructType::create(ctx.context, "Schema");
    T::TableTy = StructType::create(ctx.context, "Table");
    T::ColumnTy = StructType::create(ctx.context, "Column");
    T::ExprTy = StructType::create(ctx.context, "Expr");
    T::anonTy = StructType::create(ctx.context, "anon");
    T::anon0Ty = StructType::create(ctx.context, "anon0");
    T::AggInfoTy = StructType::create(ctx.context, "AggInfo");
    T::AggInfo_colTy = StructType::create(ctx.context, "AggInfo_col");
    T::AggInfo_funcTy = StructType::create(ctx.context, "AggInfo_func");
    T::FuncDefTy = StructType::create(ctx.context, "FuncDef");
    T::sqlite3_contextTy = StructType::create(ctx.context, "sqlite3_context");
    T::anon8Ty = StructType::create(ctx.context, "anon8");
    T::anon4Ty = StructType::create(ctx.context, "anon4");
    T::IndexTy = StructType::create(ctx.context, "Index");
    T::SelectTy = StructType::create(ctx.context, "Select");
    T::SrcList_itemTy = StructType::create(ctx.context, "SrcList_item");
    T::SrcListTy = StructType::create(ctx.context, "SrcList");
    T::anon2Ty = StructType::create(ctx.context, "anon2");
    T::IdListTy = StructType::create(ctx.context, "IdList");
    T::IdList_itemTy = StructType::create(ctx.context, "IdList_item");
    T::anon3Ty = StructType::create(ctx.context, "anon3");
    T::CteTy = StructType::create(ctx.context, "Cte");
    T::WithTy = StructType::create(ctx.context, "With");
    T::WindowTy = StructType::create(ctx.context, "Window");
    T::sColMapTy = StructType::create(ctx.context, "sColMap");
    T::FKeyTy = StructType::create(ctx.context, "FKey");
    T::ExprList_itemTy = StructType::create(ctx.context, "ExprList_item");
    T::ExprListTy = StructType::create(ctx.context, "ExprList");
    T::anon1Ty = StructType::create(ctx.context, "anon1");
    T::TriggerTy = StructType::create(ctx.context, "Trigger");
    T::TriggerStepTy = StructType::create(ctx.context, "TriggerStep");
    T::UpsertTy = StructType::create(ctx.context, "Upsert");
    T::sqlite3InitInfoTy = StructType::create(ctx.context, "sqlite3InitInfo");
    T::ParseTy = StructType::create(ctx.context, "Parse");
    T::AutoincInfoTy = StructType::create(ctx.context, "AutoincInfo");
    T::TokenTy = StructType::create(ctx.context, "Token");
    T::TriggerPrgTy = StructType::create(ctx.context, "TriggerPrg");
    T::anon6Ty = StructType::create(ctx.context, "anon6");
    T::LookasideTy = StructType::create(ctx.context, "Lookaside");
    T::LookasideSlotTy = StructType::create(ctx.context, "LookasideSlot");
    T::VTableTy = StructType::create(ctx.context, "VTable");
    T::ModuleTy = StructType::create(ctx.context, "Module");
    T::sqlite3_moduleTy = StructType::create(ctx.context, "sqlite3_module");
    T::sqlite3_index_infoTy = StructType::create(ctx.context, "sqlite3_index_info");
    T::sqlite3_index_constraintTy = StructType::create(ctx.context, "sqlite3_index_constraint");
    T::sqlite3_index_orderbyTy = StructType::create(ctx.context, "sqlite3_index_orderby");
    T::sqlite3_index_constraint_usageTy = StructType::create(ctx.context, "sqlite3_index_constraint_usage");
    T::sqlite3_vtab_cursorTy = StructType::create(ctx.context, "sqlite3_vtab_cursor");
    T::sqlite3_vtabTy = StructType::create(ctx.context, "sqlite3_vtab");
    T::HashTy = StructType::create(ctx.context, "Hash");
    T::HashElemTy = StructType::create(ctx.context, "HashElem");
    T::_htTy = StructType::create(ctx.context, "_ht");
    T::BusyHandlerTy = StructType::create(ctx.context, "BusyHandler");
    T::SavepointTy = StructType::create(ctx.context, "Savepoint");
    T::UnpackedRecordTy = StructType::create(ctx.context, "UnpackedRecord");
    T::BtreePayloadTy = StructType::create(ctx.context, "BtreePayload");
    T::InitDataTy = StructType::create(ctx.context, "InitData");


    T::i32Ty = IntegerType::get(ctx.context, 32);
    T::sqlite3_index_constraint_usagePtrTy = PointerType::get(T::sqlite3_index_constraint_usageTy, 0);
    T::VdbeOpPtrTy = PointerType::get(T::VdbeOpTy, 0);
    T::VoidTy = IntegerType::getVoidTy(ctx.context);
    T::WindowPtrTy = PointerType::get(T::WindowTy, 0);
    T::doubleTy = IntegerType::getDoubleTy(ctx.context);
    T::sqlite3_filePtrTy = PointerType::get(T::sqlite3_fileTy, 0);
    T::sqlite3_mutexTy = StructType::create(ctx.context, "sqlite3_mutex");
    T::sqlite3_modulePtrTy = PointerType::get(T::sqlite3_moduleTy, 0);
    T::sqlite3_pcache_pagePtrTy = PointerType::get(T::sqlite3_pcache_pageTy, 0);
    T::AutoincInfoPtrTy = PointerType::get(T::AutoincInfoTy, 0);
    T::DbPtrTy = PointerType::get(T::DbTy, 0);
    T::VTablePtrTy = PointerType::get(T::VTableTy, 0);
    T::LookasideSlotPtrTy = PointerType::get(T::LookasideSlotTy, 0);
    T::sqlite3PtrTy = PointerType::get(T::sqlite3Ty, 0);
    T::i16Ty = IntegerType::get(ctx.context, 16);
    T::AggInfoPtrTy = PointerType::get(T::AggInfoTy, 0);
    T::SrcListPtrTy = PointerType::get(T::SrcListTy, 0);
    T::TablePtrTy = PointerType::get(T::TableTy, 0);
    T::BtreeTy = StructType::create(ctx.context, "Btree");
    T::VdbePtrTy = PointerType::get(T::VdbeTy, 0);
    T::sqlite3_vtab_cursorPtrTy = PointerType::get(T::sqlite3_vtab_cursorTy, 0);
    T::Arr_1_SrcList_itemTy = ArrayType::get(T::SrcList_itemTy, 1);
    T::ExprPtrTy = PointerType::get(T::ExprTy, 0);
    T::HashElemPtrTy = PointerType::get(T::HashElemTy, 0);
    T::AggInfo_colPtrTy = PointerType::get(T::AggInfo_colTy, 0);
    T::i64Ty = IntegerType::get(ctx.context, 64);
    T::PagerTy = StructType::create(ctx.context, "Pager");
    T::IndexPtrTy = PointerType::get(T::IndexTy, 0);
    T::TriggerStepPtrTy = PointerType::get(T::TriggerStepTy, 0);
    T::sqlite3_index_infoPtrTy = PointerType::get(T::sqlite3_index_infoTy, 0);
    T::SavepointPtrTy = PointerType::get(T::SavepointTy, 0);
    T::UpsertPtrTy = PointerType::get(T::UpsertTy, 0);
    T::TriggerPrgPtrTy = PointerType::get(T::TriggerPrgTy, 0);
    T::sqlite3_vfsPtrTy = PointerType::get(T::sqlite3_vfsTy, 0);
    T::TriggerPtrTy = PointerType::get(T::TriggerTy, 0);
    T::VdbeCursorPtrTy = PointerType::get(T::VdbeCursorTy, 0);
    T::IdList_itemPtrTy = PointerType::get(T::IdList_itemTy, 0);
    T::SubProgramPtrTy = PointerType::get(T::SubProgramTy, 0);
    T::KeyInfoPtrTy = PointerType::get(T::KeyInfoTy, 0);
    T::BtCursorTy = StructType::create(ctx.context, "BtCursor");
    T::_htPtrTy = PointerType::get(T::_htTy, 0);
    T::RenameTokenTy = StructType::create(ctx.context, "RenameToken");
    T::sqlite3_io_methodsPtrTy = PointerType::get(T::sqlite3_io_methodsTy, 0);
    T::sqlite3_vtabPtrTy = PointerType::get(T::sqlite3_vtabTy, 0);
    T::Arr_1_sColMapTy = ArrayType::get(T::sColMapTy, 1);
    T::WithPtrTy = PointerType::get(T::WithTy, 0);
    T::Arr_2_DbTy = ArrayType::get(T::DbTy, 2);
    T::ModulePtrTy = PointerType::get(T::ModuleTy, 0);
    T::CollSeqPtrTy = PointerType::get(T::CollSeqTy, 0);
    T::AuxDataPtrTy = PointerType::get(T::AuxDataTy, 0);
    T::TableLockTy = StructType::create(ctx.context, "TableLock");
    T::FKeyPtrTy = PointerType::get(T::FKeyTy, 0);
    T::Arr_1_ExprList_itemTy = ArrayType::get(T::ExprList_itemTy, 1);
    T::SelectPtrTy = PointerType::get(T::SelectTy, 0);
    T::VtabCtxTy = StructType::create(ctx.context, "VtabCtx");
    T::i8Ty = IntegerType::get(ctx.context, 8);
    T::RowSetTy = StructType::create(ctx.context, "RowSet");
    T::IdListPtrTy = PointerType::get(T::IdListTy, 0);
    T::ParsePtrTy = PointerType::get(T::ParseTy, 0);
    T::Arr_1_CteTy = ArrayType::get(T::CteTy, 1);
    T::VdbeFramePtrTy = PointerType::get(T::VdbeFrameTy, 0);
    T::VdbeSorterTy = StructType::create(ctx.context, "VdbeSorter");
    T::SchemaPtrTy = PointerType::get(T::SchemaTy, 0);
    T::sqlite3_contextPtrTy = PointerType::get(T::sqlite3_contextTy, 0);
    T::AggInfo_funcPtrTy = PointerType::get(T::AggInfo_funcTy, 0);
    T::sqlite3_index_orderbyPtrTy = PointerType::get(T::sqlite3_index_orderbyTy, 0);
    T::sqlite3_valuePtrTy = PointerType::get(T::sqlite3_valueTy, 0);
    T::ExprListPtrTy = PointerType::get(T::ExprListTy, 0);
    T::sqlite3_index_constraintPtrTy = PointerType::get(T::sqlite3_index_constraintTy, 0);
    T::FuncDefPtrTy = PointerType::get(T::FuncDefTy, 0);
    T::ColumnPtrTy = PointerType::get(T::ColumnTy, 0);
    T::sqlite3_pcacheTy = StructType::create(ctx.context, "sqlite3_pcache");
    T::Arr_1_CollSeqPtrTy = ArrayType::get(PointerType::get(T::CollSeqTy, 0), 1);
    T::i32_Of_i32Ty = FunctionType::get(IntegerType::get(ctx.context, 32), {T::i32Ty}, false);
    T::BtreePtrTy = PointerType::get(T::BtreeTy, 0);
    T::Arr_2_i8Ty = ArrayType::get(IntegerType::get(ctx.context, 8), 2);
    T::Arr_3_i32Ty = ArrayType::get(IntegerType::get(ctx.context, 32), 3);
    T::i32_Of_sqlite3_filePtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_filePtrTy}, false);
    T::i32_Of_sqlite3_vtab_cursorPtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vtab_cursorPtrTy}, false);
    T::i32_Of_sqlite3_filePtr_i64Ty = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_filePtrTy, T::i64Ty}, false);
    T::WindowPtrPtrTy = PointerType::get(T::WindowPtrTy, 0);
    T::i32_Of_sqlite3_vtab_cursorPtr_sqlite3_contextPtr_i32Ty = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vtab_cursorPtrTy, T::sqlite3_contextPtrTy, T::i32Ty}, false);
    T::Arr_4_i8Ty = ArrayType::get(IntegerType::get(ctx.context, 8), 4);
    T::i32_Of_sqlite3_vtabPtr_i32Ty = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vtabPtrTy, T::i32Ty}, false);
    T::i32_Of_sqlite3_filePtr_i32Ty = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_filePtrTy, T::i32Ty}, false);
    T::VdbeCursorPtrPtrTy = PointerType::get(T::VdbeCursorPtrTy, 0);
    T::Arr_3_i8Ty = ArrayType::get(IntegerType::get(ctx.context, 8), 3);
    T::i16PtrTy = PointerType::get(T::i16Ty, 0);
    T::doublePtrTy = PointerType::get(T::doubleTy, 0);
    T::Arr_12_i32Ty = ArrayType::get(IntegerType::get(ctx.context, 32), 12);
    T::sqlite3_valuePtrPtrTy = PointerType::get(T::sqlite3_valuePtrTy, 0);
    T::i32PtrTy = PointerType::get(T::i32Ty, 0);
    T::BtCursorPtrTy = PointerType::get(T::BtCursorTy, 0);
    T::Void_Of_VoidTy = FunctionType::get(IntegerType::getVoidTy(ctx.context), {}, false);
    T::VTablePtrPtrTy = PointerType::get(T::VTablePtrTy, 0);
    T::Arr_8_i32Ty = ArrayType::get(IntegerType::get(ctx.context, 32), 8);
    T::i32_Of_sqlite3_filePtr_i32_i32_i32Ty = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_filePtrTy, T::i32Ty, T::i32Ty, T::i32Ty}, false);
    T::i32_Of_sqlite3_vtabPtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vtabPtrTy}, false);
    T::sqlite3_vtab_cursorPtrPtrTy = PointerType::get(T::sqlite3_vtab_cursorPtrTy, 0);
    T::sqlite3_vtabPtrPtrTy = PointerType::get(T::sqlite3_vtabPtrTy, 0);
    T::Arr_2_i32Ty = ArrayType::get(IntegerType::get(ctx.context, 32), 2);
    T::sqlite3_pcachePtrTy = PointerType::get(T::sqlite3_pcacheTy, 0);
    T::TablePtrPtrTy = PointerType::get(T::TablePtrTy, 0);
    T::Arr_2_TriggerPtrTy = ArrayType::get(PointerType::get(T::TriggerTy, 0), 2);
    T::TableLockPtrTy = PointerType::get(T::TableLockTy, 0);
    T::i32_Of_VoidTy = FunctionType::get(IntegerType::get(ctx.context, 32), {}, false);
    T::i64PtrTy = PointerType::get(T::i64Ty, 0);
    T::RenameTokenPtrTy = PointerType::get(T::RenameTokenTy, 0);
    T::Void_Of_sqlite3_contextPtrTy = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::sqlite3_contextPtrTy}, false);
    T::Void_Of_sqlite3_filePtrTy = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::sqlite3_filePtrTy}, false);
    T::i32_Of_sqlite3_vtabPtr_sqlite3_index_infoPtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vtabPtrTy, T::sqlite3_index_infoPtrTy}, false);
    T::sqlite3_mutexPtrTy = PointerType::get(T::sqlite3_mutexTy, 0);
    T::i8PtrTy = PointerType::get(T::i8Ty, 0);
    T::VtabCtxPtrTy = PointerType::get(T::VtabCtxTy, 0);
    T::Arr_7_i32Ty = ArrayType::get(IntegerType::get(ctx.context, 32), 7);
    T::Arr_1_i32Ty = ArrayType::get(IntegerType::get(ctx.context, 32), 1);
    T::i32_Of_sqlite3_vfsPtr_i32Ty = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vfsPtrTy, T::i32Ty}, false);
    T::Arr_1_sqlite3_valuePtrTy = ArrayType::get(PointerType::get(T::sqlite3_valueTy, 0), 1);
    T::Void_Of_sqlite3_contextPtrPtrTy = PointerType::get(T::Void_Of_sqlite3_contextPtrTy, 0);
    T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32Ty = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::sqlite3_pcachePtrTy, T::sqlite3_pcache_pagePtrTy, T::i32Ty}, false);
    T::i32_Of_sqlite3_vtab_cursorPtr_sqlite3_contextPtr_i32PtrTy = PointerType::get(T::i32_Of_sqlite3_vtab_cursorPtr_sqlite3_contextPtr_i32Ty, 0);
    T::sqlite3_pcache_pagePtr_Of_sqlite3_pcachePtr_i32_i32Ty = FunctionType::get(PointerType::get(T::sqlite3_pcache_pageTy, 0), {T::sqlite3_pcachePtrTy, T::i32Ty, T::i32Ty}, false);
    T::i8Ptr_Of_i32Ty = FunctionType::get(PointerType::get(T::i8Ty, 0), {T::i32Ty}, false);
    T::i32_Of_i8Ptr_i32_i8Ptr_i32_i8PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::i8PtrTy, T::i32Ty, T::i8PtrTy, T::i32Ty, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_filePtr_i64_i8PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_filePtrTy, T::i64Ty, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_vfsPtr_i64PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vfsPtrTy, T::i64PtrTy}, false);
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_sqlite3_filePtr_i32_i32PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vfsPtrTy, T::i8PtrTy, T::sqlite3_filePtrTy, T::i32Ty, T::i32PtrTy}, false);
    T::Void_Of_sqlite3_pcachePtrTy = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::sqlite3_pcachePtrTy}, false);
    T::i32_Of_sqlite3_vtab_cursorPtr_i64PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vtab_cursorPtrTy, T::i64PtrTy}, false);
    T::i32_Of_sqlite3_vtabPtr_sqlite3_vtab_cursorPtrPtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vtabPtrTy, T::sqlite3_vtab_cursorPtrPtrTy}, false);
    T::i32_Of_i32_i8Ptr_i8Ptr_i8PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::i32Ty, T::i8PtrTy, T::i8PtrTy, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_vtab_cursorPtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vtab_cursorPtrTy, 0);
    T::Void_Of_i8PtrTy = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::i8PtrTy}, false);
    T::PxFunctionPtrTy = FunctionType::get(T::i8PtrTy, {T::sqlite3_contextPtrTy, T::i32Ty, T::sqlite3_valuePtrPtrTy}, false);
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i32PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vfsPtrTy, T::i8PtrTy, T::i32Ty, T::i32PtrTy}, false);
    T::sqlite3_pcachePtr_Of_i32_i32_i32Ty = FunctionType::get(PointerType::get(T::sqlite3_pcacheTy, 0), {T::i32Ty, T::i32Ty, T::i32Ty}, false);
    T::i32_Of_i8Ptr_sqlite3Ptr_i8Ptr_i32Ty = FunctionType::get(IntegerType::get(ctx.context, 32), {T::i8PtrTy, T::sqlite3PtrTy, T::i8PtrTy, T::i32Ty}, false);
    T::i32_Of_i8PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::i8PtrTy}, false);
    T::Void_Of_sqlite3_mutexPtrTy = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::sqlite3_mutexPtrTy}, false);
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32Ty = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vfsPtrTy, T::i8PtrTy, T::i32Ty}, false);
    T::i32_Of_sqlite3_vfsPtr_i32_i8PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vfsPtrTy, T::i32Ty, T::i8PtrTy}, false);
    T::Void_Of_Void_Of_Sqlite3_Vfs_i8PtrTy = PointerType::get(FunctionType::get(FunctionType::get(IntegerType::getVoidTy(ctx.context), {}, false), { T::sqlite3_vfsPtrTy, T::i8PtrTy }, false), 0);
    T::i32_Of_sqlite3_filePtr_i32_i8PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_filePtrTy, T::i32Ty, T::i8PtrTy}, false);
    T::Void_Of_sqlite3_pcachePtr_i32Ty = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::sqlite3_pcachePtrTy, T::i32Ty}, false);
    T::i32_Of_i8Ptr_i32Ty = FunctionType::get(IntegerType::get(ctx.context, 32), {T::i8PtrTy, T::i32Ty}, false);
    T::Void_Of_VoidPtrTy = PointerType::get(T::Void_Of_VoidTy, 0);
    T::i8Ptr_Of_i8Ptr_i32Ty = FunctionType::get(PointerType::get(T::i8Ty, 0), {T::i8PtrTy, T::i32Ty}, false);
    T::i32_Of_sqlite3_filePtrPtrTy = PointerType::get(T::i32_Of_sqlite3_filePtrTy, 0);
    T::i32_Of_sqlite3_pcachePtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_pcachePtrTy}, false);
    T::i32_Of_sqlite3_vtabPtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vtabPtrTy, 0);
    T::i32_Of_sqlite3_vtabPtr_i8PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vtabPtrTy, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_vtab_cursorPtr_i32_i8Ptr_i32_sqlite3_valuePtrPtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vtab_cursorPtrTy, T::i32Ty, T::i8PtrTy, T::i32Ty, T::sqlite3_valuePtrPtrTy}, false);
    T::i32_Of_i8Ptr_i32_i8Ptr_i8Ptr_i8Ptr_i8PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::i8PtrTy, T::i32Ty, T::i8PtrTy, T::i8PtrTy, T::i8PtrTy, T::i8PtrTy}, false);
    T::Void_Of_sqlite3_vfsPtr_i8PtrTy = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::sqlite3_vfsPtrTy, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_filePtr_i32_i32_i32PtrTy = PointerType::get(T::i32_Of_sqlite3_filePtr_i32_i32_i32Ty, 0);
    T::i32_Of_sqlite3_vfsPtr_doublePtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vfsPtrTy, T::doublePtrTy}, false);
    T::Void_Of_i8Ptr_i8Ptr_i64Ty = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::i8PtrTy, T::i8PtrTy, T::i64Ty}, false);
    T::Void_Of_sqlite3_contextPtr_i32_sqlite3_valuePtrPtrTy = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::sqlite3_contextPtrTy, T::i32Ty, T::sqlite3_valuePtrPtrTy}, false);
    T::i32_Of_sqlite3_mutexPtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_mutexPtrTy}, false);
    T::i32_Of_sqlite3_vtabPtr_sqlite3_index_infoPtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vtabPtr_sqlite3_index_infoPtrTy, 0);
    T::i8PtrPtrTy = PointerType::get(T::i8PtrTy, 0);
    T::i32_Of_VoidPtrTy = PointerType::get(T::i32_Of_VoidTy, 0);
    T::Void_Of_i8Ptr_sqlite3Ptr_i32_i8PtrTy = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::i8PtrTy, T::sqlite3PtrTy, T::i32Ty, T::i8PtrTy}, false);
    T::Void_Of_sqlite3_filePtrPtrTy = PointerType::get(T::Void_Of_sqlite3_filePtrTy, 0);
    T::Void_Of_sqlite3_vfsPtr_i32_i8PtrTy = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::sqlite3_vfsPtrTy, T::i32Ty, T::i8PtrTy}, false);
    T::Void_Of_Void_Of_Sqlite3_Vfs_i8Ptr_i8PtrTy = PointerType::get(FunctionType::get(FunctionType::get(IntegerType::getVoidTy(ctx.context), {}, false), { T::sqlite3_vfsPtrTy, T::i8PtrTy, T::i8PtrTy }, false), 0);
    T::i32_Of_i32PtrTy = PointerType::get(T::i32_Of_i32Ty, 0);
    T::i32_Of_sqlite3_filePtr_i32PtrTy = PointerType::get(T::i32_Of_sqlite3_filePtr_i32Ty, 0);
    T::Void_Of_i8Ptr_i32_i8PtrTy = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::i8PtrTy, T::i32Ty, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_filePtr_i8Ptr_i32_i64Ty = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_filePtrTy, T::i8PtrTy, T::i32Ty, T::i64Ty}, false);
    T::i32_Of_sqlite3_vtabPtr_i32PtrTy = PointerType::get(T::i32_Of_sqlite3_vtabPtr_i32Ty, 0);
    T::i8Ptr_Of_sqlite3_vfsPtr_i8PtrTy = FunctionType::get(PointerType::get(T::i8Ty, 0), {T::sqlite3_vfsPtrTy, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_filePtr_i64PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_filePtrTy, T::i64PtrTy}, false);
    T::sqlite3_mutexPtr_Of_i32Ty = FunctionType::get(PointerType::get(T::sqlite3_mutexTy, 0), {T::i32Ty}, false);
    T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32_i32Ty = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::sqlite3_pcachePtrTy, T::sqlite3_pcache_pagePtrTy, T::i32Ty, T::i32Ty}, false);
    T::Void_Of_i8Ptr_i32_i8Ptr_i8Ptr_i64Ty = FunctionType::get(IntegerType::getVoidTy(ctx.context), {T::i8PtrTy, T::i32Ty, T::i8PtrTy, T::i8PtrTy, T::i64Ty}, false);
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i8PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vfsPtrTy, T::i8PtrTy, T::i32Ty, T::i8PtrTy}, false);
    T::i32_Of_sqlite3_vtabPtr_i32_sqlite3_valuePtrPtr_i64PtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vtabPtrTy, T::i32Ty, T::sqlite3_valuePtrPtrTy, T::i64PtrTy}, false);
    T::i32_Of_sqlite3_vfsPtr_i32PtrTy = PointerType::get(T::i32_Of_sqlite3_vfsPtr_i32Ty, 0);
    T::i32_Of_i8Ptr_i32_i8Ptr_i32_i8PtrPtrTy = PointerType::get(T::i32_Of_i8Ptr_i32_i8Ptr_i32_i8PtrTy, 0);
    T::i32_Of_i32_i8Ptr_i8Ptr_i8PtrPtrTy = PointerType::get(T::i32_Of_i32_i8Ptr_i8Ptr_i8PtrTy, 0);
    T::i32_Of_sqlite3_vtabPtr_i8PtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vtabPtr_i8PtrTy, 0);
    T::i8Ptr_Of_i32PtrTy = PointerType::get(T::i8Ptr_Of_i32Ty, 0);
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_sqlite3_filePtr_i32_i32PtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vfsPtr_i8Ptr_sqlite3_filePtr_i32_i32PtrTy, 0);
    T::i32_Of_sqlite3_filePtr_i32PtrPtrTy = PointerType::get(T::i32_Of_sqlite3_filePtr_i32PtrTy, 0);
    T::i32_Of_sqlite3_filePtr_i64_i8PtrPtrTy = PointerType::get(T::i32_Of_sqlite3_filePtr_i64_i8PtrTy, 0);
    T::i32_Of_sqlite3_filePtr_i64PtrPtrTy = PointerType::get(T::i32_Of_sqlite3_filePtr_i64PtrTy, 0);
    T::Void_Of_sqlite3_mutexPtrPtrTy = PointerType::get(T::Void_Of_sqlite3_mutexPtrTy, 0);
    T::i32_Of_sqlite3_filePtr_i32_i8PtrPtrTy = PointerType::get(T::i32_Of_sqlite3_filePtr_i32_i8PtrTy, 0);
    T::Void_Of_i8Ptr_sqlite3Ptr_i32_i8PtrPtrTy = PointerType::get(T::Void_Of_i8Ptr_sqlite3Ptr_i32_i8PtrTy, 0);
    T::i32_Of_sqlite3_vfsPtr_i32_i8PtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vfsPtr_i32_i8PtrTy, 0);
    T::i32_Of_sqlite3_filePtr_i64_i32_i8PtrPtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_filePtrTy, T::i64Ty, T::i32Ty, T::i8PtrPtrTy}, false);
    T::sqlite3_pcachePtr_Of_i32_i32_i32PtrTy = PointerType::get(T::sqlite3_pcachePtr_Of_i32_i32_i32Ty, 0);
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_Void_Of_VoidPtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vfsPtrTy, T::i8PtrTy, T::Void_Of_VoidPtrTy}, false);
    T::i8Ptr_Of_sqlite3_vfsPtr_i8PtrPtrTy = PointerType::get(T::i8Ptr_Of_sqlite3_vfsPtr_i8PtrTy, 0);
    T::i32_Of_i8Ptr_i32PtrTy = PointerType::get(T::i32_Of_i8Ptr_i32Ty, 0);
    T::i32_Of_sqlite3_vtab_cursorPtr_i32_i8Ptr_i32_sqlite3_valuePtrPtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vtab_cursorPtr_i32_i8Ptr_i32_sqlite3_valuePtrPtrTy, 0);
    T::Void_Of_i8PtrPtrTy = PointerType::get(T::Void_Of_i8PtrTy, 0);
    T::i32_Of_i8Ptr_i32_i8Ptr_i8Ptr_i8Ptr_i8PtrPtrTy = PointerType::get(T::i32_Of_i8Ptr_i32_i8Ptr_i8Ptr_i8Ptr_i8PtrTy, 0);
    T::i32_Of_sqlite3_mutexPtrPtrTy = PointerType::get(T::i32_Of_sqlite3_mutexPtrTy, 0);
    T::i32_Of_sqlite3_filePtr_i8Ptr_i32_i64PtrTy = PointerType::get(T::i32_Of_sqlite3_filePtr_i8Ptr_i32_i64Ty, 0);
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i32PtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i32PtrTy, 0);
    T::Void_Of_sqlite3_vfsPtr_i32_i8PtrPtrTy = PointerType::get(T::Void_Of_sqlite3_vfsPtr_i32_i8PtrTy, 0);
    T::i32_Of_sqlite3_filePtr_i32_i32_i32_i8PtrPtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_filePtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i8PtrPtrTy}, false);
    T::i32_Of_sqlite3_vtabPtr_i32_i8Ptr_PxFunctionPtr_i8PtrPtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3_vtabPtrTy, T::i32Ty, T::i8PtrTy, T::PxFunctionPtrTy, T::i8PtrPtrTy}, false);
    T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32_i32PtrTy = PointerType::get(T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32_i32Ty, 0);
    T::Void_Of_i8Ptr_i32_i8PtrPtrTy = PointerType::get(T::Void_Of_i8Ptr_i32_i8PtrTy, 0);
    T::i32_Of_sqlite3_vtab_cursorPtr_i64PtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vtab_cursorPtr_i64PtrTy, 0);
    T::Void_Of_i8Ptr_i32_i8Ptr_i8Ptr_i64PtrTy = PointerType::get(T::Void_Of_i8Ptr_i32_i8Ptr_i8Ptr_i64Ty, 0);
    T::Void_Of_sqlite3_pcachePtr_i32PtrTy = PointerType::get(T::Void_Of_sqlite3_pcachePtr_i32Ty, 0);
    T::i32_Of_sqlite3Ptr_i8Ptr_i32_i8PtrPtr_sqlite3_vtabPtrPtr_i8PtrPtrTy = FunctionType::get(IntegerType::get(ctx.context, 32), {T::sqlite3PtrTy, T::i8PtrTy, T::i32Ty, T::i8PtrPtrTy, T::sqlite3_vtabPtrPtrTy, T::i8PtrPtrTy}, false);
    T::i32_Of_sqlite3_pcachePtrPtrTy = PointerType::get(T::i32_Of_sqlite3_pcachePtrTy, 0);
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32PtrTy = PointerType::get(T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32Ty, 0);
    T::Void_Of_sqlite3_vfsPtr_i8PtrPtrTy = PointerType::get(T::Void_Of_sqlite3_vfsPtr_i8PtrTy, 0);
    T::i32_Of_i8Ptr_sqlite3Ptr_i8Ptr_i32PtrTy = PointerType::get(T::i32_Of_i8Ptr_sqlite3Ptr_i8Ptr_i32Ty, 0);
    T::i32_Of_sqlite3_vtabPtr_sqlite3_vtab_cursorPtrPtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vtabPtr_sqlite3_vtab_cursorPtrPtrTy, 0);
    T::sqlite3_mutexPtr_Of_i32PtrTy = PointerType::get(T::sqlite3_mutexPtr_Of_i32Ty, 0);
    T::sqlite3_pcache_pagePtr_Of_sqlite3_pcachePtr_i32_i32PtrTy = PointerType::get(T::sqlite3_pcache_pagePtr_Of_sqlite3_pcachePtr_i32_i32Ty, 0);
    T::i32_Of_sqlite3_vfsPtr_doublePtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vfsPtr_doublePtrTy, 0);
    T::Void_Of_i8Ptr_i8Ptr_i64PtrTy = PointerType::get(T::Void_Of_i8Ptr_i8Ptr_i64Ty, 0);
    T::i32_Of_i8PtrPtrTy = PointerType::get(T::i32_Of_i8PtrTy, 0);
    T::Void_Of_sqlite3_pcachePtrPtrTy = PointerType::get(T::Void_Of_sqlite3_pcachePtrTy, 0);
    T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32PtrTy = PointerType::get(T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32Ty, 0);
    T::i8Ptr_Of_i8Ptr_i32PtrTy = PointerType::get(T::i8Ptr_Of_i8Ptr_i32Ty, 0);
    T::i32_Of_sqlite3_vfsPtr_i64PtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vfsPtr_i64PtrTy, 0);
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i8PtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i8PtrTy, 0);
    T::Void_Of_sqlite3_contextPtr_i32_sqlite3_valuePtrPtrPtrTy = PointerType::get(T::Void_Of_sqlite3_contextPtr_i32_sqlite3_valuePtrPtrTy, 0);
    T::i32_Of_sqlite3_vtabPtr_i32_sqlite3_valuePtrPtr_i64PtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vtabPtr_i32_sqlite3_valuePtrPtr_i64PtrTy, 0);
    T::i32_Of_sqlite3_filePtr_i32_i32_i32_i8PtrPtrPtrTy = PointerType::get(T::i32_Of_sqlite3_filePtr_i32_i32_i32_i8PtrPtrTy, 0);
    T::i32_Of_sqlite3_filePtr_i64_i32_i8PtrPtrPtrTy = PointerType::get(T::i32_Of_sqlite3_filePtr_i64_i32_i8PtrPtrTy, 0);
    T::i32_Of_sqlite3Ptr_i8Ptr_i32_i8PtrPtr_sqlite3_vtabPtrPtr_i8PtrPtrPtrTy = PointerType::get(T::i32_Of_sqlite3Ptr_i8Ptr_i32_i8PtrPtr_sqlite3_vtabPtrPtr_i8PtrPtrTy, 0);
    T::i32_Of_sqlite3_vfsPtr_i8Ptr_Void_Of_VoidPtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vfsPtr_i8Ptr_Void_Of_VoidPtrTy, 0);
    T::i32_Of_sqlite3_vtabPtr_i32_i8Ptr_PxFunctionPtr_i8PtrPtrPtrTy = PointerType::get(T::i32_Of_sqlite3_vtabPtr_i32_i8Ptr_PxFunctionPtr_i8PtrPtrTy, 0);
    T::Sqlite3ConfigTy->setBody({ T::i32Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::sqlite3_mem_methodsTy, T::sqlite3_mutex_methodsTy, T::sqlite3_pcache_methods2Ty, T::i8PtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i64Ty, T::i64Ty, T::i8PtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::sqlite3_mutexPtrTy, T::Void_Of_i8Ptr_i32_i8PtrPtrTy, T::i8PtrTy, T::i32_Of_i32PtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty }, false);
    T::sqlite3_mem_methodsTy->setBody({ T::i8Ptr_Of_i32PtrTy, T::Void_Of_i8PtrPtrTy, T::i8Ptr_Of_i8Ptr_i32PtrTy, T::i32_Of_i8PtrPtrTy, T::i32_Of_i32PtrTy, T::i32_Of_i8PtrPtrTy, T::Void_Of_i8PtrPtrTy, T::i8PtrTy }, false);
    T::sqlite3_mutex_methodsTy->setBody({ T::i32_Of_VoidPtrTy, T::i32_Of_VoidPtrTy, T::sqlite3_mutexPtr_Of_i32PtrTy, T::Void_Of_sqlite3_mutexPtrPtrTy, T::Void_Of_sqlite3_mutexPtrPtrTy, T::i32_Of_sqlite3_mutexPtrPtrTy, T::Void_Of_sqlite3_mutexPtrPtrTy, T::i32_Of_sqlite3_mutexPtrPtrTy, T::i32_Of_sqlite3_mutexPtrPtrTy }, false);
    T::sqlite3_pcache_methods2Ty->setBody({ T::i32Ty, T::i8PtrTy, T::i32_Of_i8PtrPtrTy, T::Void_Of_i8PtrPtrTy, T::sqlite3_pcachePtr_Of_i32_i32_i32PtrTy, T::Void_Of_sqlite3_pcachePtr_i32PtrTy, T::i32_Of_sqlite3_pcachePtrPtrTy, T::sqlite3_pcache_pagePtr_Of_sqlite3_pcachePtr_i32_i32PtrTy, T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32PtrTy, T::Void_Of_sqlite3_pcachePtr_sqlite3_pcache_pagePtr_i32_i32PtrTy, T::Void_Of_sqlite3_pcachePtr_i32PtrTy, T::Void_Of_sqlite3_pcachePtrPtrTy, T::Void_Of_sqlite3_pcachePtrPtrTy }, false);
    T::sqlite3_pcache_pageTy->setBody({ T::i8PtrTy, T::i8PtrTy }, false);
    T::DbTy->setBody({ T::i8PtrTy, T::BtreePtrTy, T::i8Ty, T::i8Ty, T::SchemaPtrTy }, false);
    T::sqlite3_valueTy->setBody({ T::MemValueTy, T::i16Ty, T::i8Ty, T::i8Ty, T::i32Ty, T::i8PtrTy, T::i8PtrTy, T::i32Ty, T::i32Ty, T::sqlite3PtrTy, T::Void_Of_i8PtrPtrTy }, false);
    T::MemValueTy->setBody({ T::doubleTy }, false);
    T::sqlite3Ty->setBody({ T::sqlite3_vfsPtrTy, T::VdbePtrTy, T::CollSeqPtrTy, T::sqlite3_mutexPtrTy, T::DbPtrTy, T::i32Ty, T::i32Ty, T::i64Ty, T::i64Ty, T::i64Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i16Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::Arr_12_i32Ty, T::i32Ty, T::sqlite3InitInfoTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i8PtrPtrTy, T::i32_Of_i32_i8Ptr_i8Ptr_i8PtrPtrTy, T::i8PtrTy, T::Void_Of_i8Ptr_i8Ptr_i64PtrTy, T::i8PtrTy, T::i8PtrTy, T::i32_Of_i8PtrPtrTy, T::i8PtrTy, T::Void_Of_i8PtrPtrTy, T::i8PtrTy, T::Void_Of_i8Ptr_i32_i8Ptr_i8Ptr_i64PtrTy, T::ParsePtrTy, T::i32_Of_i8Ptr_sqlite3Ptr_i8Ptr_i32PtrTy, T::i8PtrTy, T::Void_Of_i8Ptr_sqlite3Ptr_i32_i8PtrPtrTy, T::Void_Of_i8Ptr_sqlite3Ptr_i32_i8PtrPtrTy, T::i8PtrTy, T::sqlite3_valuePtrTy, T::anon6Ty, T::LookasideTy, T::i32_Of_i8Ptr_i32_i8Ptr_i8Ptr_i8Ptr_i8PtrPtrTy, T::i8PtrTy, T::i32_Of_i8PtrPtrTy, T::i8PtrTy, T::i32Ty, T::i32Ty, T::HashTy, T::VtabCtxPtrTy, T::VTablePtrPtrTy, T::VTablePtrTy, T::HashTy, T::HashTy, T::BusyHandlerTy, T::Arr_2_DbTy, T::SavepointPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i64Ty, T::i64Ty, T::i32PtrTy }, false);
    T::sqlite3_vfsTy->setBody({ T::i32Ty, T::i32Ty, T::i32Ty, T::sqlite3_vfsPtrTy, T::i8PtrTy, T::i8PtrTy, T::i32_Of_sqlite3_vfsPtr_i8Ptr_sqlite3_filePtr_i32_i32PtrPtrTy, T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32PtrTy, T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i32PtrPtrTy, T::i32_Of_sqlite3_vfsPtr_i8Ptr_i32_i8PtrPtrTy, T::i8Ptr_Of_sqlite3_vfsPtr_i8PtrPtrTy, T::Void_Of_sqlite3_vfsPtr_i32_i8PtrPtrTy, T::Void_Of_Void_Of_Sqlite3_Vfs_i8Ptr_i8PtrTy, T::Void_Of_sqlite3_vfsPtr_i8PtrPtrTy, T::i32_Of_sqlite3_vfsPtr_i32_i8PtrPtrTy, T::i32_Of_sqlite3_vfsPtr_i32PtrTy, T::i32_Of_sqlite3_vfsPtr_doublePtrPtrTy, T::i32_Of_sqlite3_vfsPtr_i32_i8PtrPtrTy, T::i32_Of_sqlite3_vfsPtr_i64PtrPtrTy, T::i32_Of_sqlite3_vfsPtr_i8Ptr_Void_Of_VoidPtrPtrTy, T::Void_Of_Void_Of_Sqlite3_Vfs_i8PtrTy, T::i8Ptr_Of_sqlite3_vfsPtr_i8PtrPtrTy }, false);
    T::sqlite3_fileTy->setBody({ T::sqlite3_io_methodsPtrTy }, false);
    T::sqlite3_io_methodsTy->setBody({ T::i32Ty, T::i32_Of_sqlite3_filePtrPtrTy, T::i32_Of_sqlite3_filePtr_i8Ptr_i32_i64PtrTy, T::i32_Of_sqlite3_filePtr_i8Ptr_i32_i64PtrTy, T::i32_Of_sqlite3_filePtr_i64PtrTy, T::i32_Of_sqlite3_filePtr_i32PtrTy, T::i32_Of_sqlite3_filePtr_i64PtrPtrTy, T::i32_Of_sqlite3_filePtr_i32PtrTy, T::i32_Of_sqlite3_filePtr_i32PtrTy, T::i32_Of_sqlite3_filePtr_i32PtrPtrTy, T::i32_Of_sqlite3_filePtr_i32_i8PtrPtrTy, T::i32_Of_sqlite3_filePtrPtrTy, T::i32_Of_sqlite3_filePtrPtrTy, T::i32_Of_sqlite3_filePtr_i32_i32_i32_i8PtrPtrPtrTy, T::i32_Of_sqlite3_filePtr_i32_i32_i32PtrTy, T::Void_Of_sqlite3_filePtrPtrTy, T::i32_Of_sqlite3_filePtr_i32PtrTy, T::i32_Of_sqlite3_filePtr_i64_i32_i8PtrPtrPtrTy, T::i32_Of_sqlite3_filePtr_i64_i8PtrPtrTy }, false);
    T::VdbeTy->setBody({ T::sqlite3PtrTy, T::VdbePtrTy, T::VdbePtrTy, T::ParsePtrTy, T::i16Ty, T::Arr_2_i8Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::Arr_4_i8Ty, T::i64Ty, T::i64Ty, T::i64Ty, T::i64Ty, T::sqlite3_valuePtrTy, T::sqlite3_valuePtrPtrTy, T::VdbeCursorPtrPtrTy, T::sqlite3_valuePtrTy, T::VdbeOpPtrTy, T::i32Ty, T::i32Ty, T::sqlite3_valuePtrTy, T::sqlite3_valuePtrTy, T::i8PtrTy, T::i32PtrTy, T::i64Ty, T::i16Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i16Ty, T::i8Ty, T::i32Ty, T::i32Ty, T::Arr_7_i32Ty, T::Arr_4_i8Ty, T::i8PtrTy, T::i8PtrTy, T::VdbeFramePtrTy, T::VdbeFramePtrTy, T::i32Ty, T::i32Ty, T::SubProgramPtrTy, T::AuxDataPtrTy }, true);
    T::VdbeCursorTy->setBody({ T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::BtreePtrTy, T::i64Ty, T::i32PtrTy, T::i32Ty, T::i32Ty, T::VdbeCursorPtrTy, T::anon7Ty, T::KeyInfoPtrTy, T::i32Ty, T::i32Ty, T::i16Ty, T::i16Ty, T::i64Ty, T::i32PtrTy, T::i8PtrTy, T::i32Ty, T::i32Ty, T::Arr_1_i32Ty }, false);
    T::anon7Ty->setBody({ T::BtCursorPtrTy }, false);
    T::KeyInfoTy->setBody({ T::i32Ty, T::i8Ty, T::i16Ty, T::i16Ty, T::sqlite3PtrTy, T::i8PtrTy, T::Arr_1_CollSeqPtrTy }, false);
    T::VdbeOpTy->setBody({ T::i8Ty, T::i8Ty, T::i16Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::p4unionTy }, false);
    T::p4unionTy->setBody({ T::i8PtrTy }, false);
    T::VdbeFrameTy->setBody({ T::VdbePtrTy, T::VdbeFramePtrTy, T::VdbeOpPtrTy, T::i64PtrTy, T::sqlite3_valuePtrTy, T::VdbeCursorPtrPtrTy, T::i8PtrTy, T::i8PtrTy, T::i64Ty, T::AuxDataPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty }, false);
    T::SubProgramTy->setBody({ T::VdbeOpPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i8PtrTy, T::i8PtrTy, T::SubProgramPtrTy }, false);
    T::AuxDataTy->setBody({ T::i32Ty, T::i32Ty, T::i8PtrTy, T::Void_Of_i8PtrPtrTy, T::AuxDataPtrTy }, false);
    T::CollSeqTy->setBody({ T::i8PtrTy, T::i8Ty, T::i8PtrTy, T::i32_Of_i8Ptr_i32_i8Ptr_i32_i8PtrPtrTy, T::Void_Of_i8PtrPtrTy }, false);
    T::SchemaTy->setBody({ T::i32Ty, T::i32Ty, T::HashTy, T::HashTy, T::HashTy, T::HashTy, T::TablePtrTy, T::i8Ty, T::i8Ty, T::i16Ty, T::i32Ty }, false);
    T::TableTy->setBody({ T::i8PtrTy, T::ColumnPtrTy, T::IndexPtrTy, T::SelectPtrTy, T::FKeyPtrTy, T::i8PtrTy, T::ExprListPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i16Ty, T::i16Ty, T::i16Ty, T::i16Ty, T::i16Ty, T::i8Ty, T::i32Ty, T::i32Ty, T::i8PtrPtrTy, T::VTablePtrTy, T::TriggerPtrTy, T::SchemaPtrTy, T::TablePtrTy }, false);
    T::ColumnTy->setBody({ T::i8PtrTy, T::ExprPtrTy, T::i8PtrTy, T::i8Ty, T::i8Ty, T::i8Ty, T::i16Ty }, false);
    T::ExprTy->setBody({ T::i8Ty, T::i8Ty, T::i8Ty, T::i32Ty, T::anonTy, T::ExprPtrTy, T::ExprPtrTy, T::anon0Ty, T::i32Ty, T::i32Ty, T::i16Ty, T::i16Ty, T::i16Ty, T::AggInfoPtrTy, T::anon4Ty }, false);
    T::anonTy->setBody({ T::i8PtrTy }, false);
    T::anon0Ty->setBody({ T::ExprListPtrTy }, false);
    T::AggInfoTy->setBody({ T::i8Ty, T::i8Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::ExprListPtrTy, T::AggInfo_colPtrTy, T::i32Ty, T::i32Ty, T::AggInfo_funcPtrTy, T::i32Ty }, false);
    T::AggInfo_colTy->setBody({ T::TablePtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::ExprPtrTy }, false);
    T::AggInfo_funcTy->setBody({ T::ExprPtrTy, T::FuncDefPtrTy, T::i32Ty, T::i32Ty }, false);
    T::FuncDefTy->setBody({ T::i8Ty, T::i32Ty, T::i8PtrTy, T::FuncDefPtrTy, T::Void_Of_sqlite3_contextPtr_i32_sqlite3_valuePtrPtrPtrTy, T::Void_Of_sqlite3_contextPtrPtrTy, T::Void_Of_sqlite3_contextPtrPtrTy, T::Void_Of_sqlite3_contextPtr_i32_sqlite3_valuePtrPtrPtrTy, T::i8PtrTy, T::anon8Ty }, false);
    T::sqlite3_contextTy->setBody({ T::sqlite3_valuePtrTy, T::FuncDefPtrTy, T::sqlite3_valuePtrTy, T::VdbePtrTy, T::i32Ty, T::i32Ty, T::i8Ty, T::i8Ty, T::Arr_1_sqlite3_valuePtrTy }, false);
    T::anon8Ty->setBody({ T::FuncDefPtrTy }, false);
    T::anon4Ty->setBody({ T::TablePtrTy }, false);
    T::IndexTy->setBody({ T::i8PtrTy, T::i16PtrTy, T::i16PtrTy, T::TablePtrTy, T::i8PtrTy, T::IndexPtrTy, T::SchemaPtrTy, T::i8PtrTy, T::i8PtrPtrTy, T::ExprPtrTy, T::ExprListPtrTy, T::i32Ty, T::i16Ty, T::i16Ty, T::i16Ty, T::i8Ty, T::i16Ty, T::Arr_3_i8Ty, T::i64Ty }, true);
    T::SelectTy->setBody({ T::i8Ty, T::i16Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::Arr_2_i32Ty, T::ExprListPtrTy, T::SrcListPtrTy, T::ExprPtrTy, T::ExprListPtrTy, T::ExprPtrTy, T::ExprListPtrTy, T::SelectPtrTy, T::SelectPtrTy, T::ExprPtrTy, T::WithPtrTy, T::WindowPtrTy, T::WindowPtrTy }, false);
    T::SrcList_itemTy->setBody({ T::SchemaPtrTy, T::i8PtrTy, T::i8PtrTy, T::i8PtrTy, T::TablePtrTy, T::SelectPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::anon2Ty, T::i32Ty, T::ExprPtrTy, T::IdListPtrTy, T::i64Ty, T::anon3Ty, T::IndexPtrTy }, false);
    T::SrcListTy->setBody({ T::i32Ty, T::i32Ty, T::Arr_1_SrcList_itemTy }, false);
    T::anon2Ty->setBody({ T::i8Ty, T::i8Ty, T::Arr_2_i8Ty }, false);
    T::IdListTy->setBody({ T::IdList_itemPtrTy, T::i32Ty }, false);
    T::IdList_itemTy->setBody({ T::i8PtrTy, T::i32Ty }, false);
    T::anon3Ty->setBody({ T::i8PtrTy }, false);
    T::CteTy->setBody({ T::i8PtrTy, T::ExprListPtrTy, T::SelectPtrTy, T::i8PtrTy }, false);
    T::WithTy->setBody({ T::i32Ty, T::WithPtrTy, T::Arr_1_CteTy }, false);
    T::WindowTy->setBody({ T::i8PtrTy, T::i8PtrTy, T::ExprListPtrTy, T::ExprListPtrTy, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::ExprPtrTy, T::ExprPtrTy, T::WindowPtrPtrTy, T::WindowPtrTy, T::ExprPtrTy, T::FuncDefPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::ExprPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i8Ty }, false);
    T::sColMapTy->setBody({ T::i32Ty, T::i8PtrTy }, false);
    T::FKeyTy->setBody({ T::TablePtrTy, T::FKeyPtrTy, T::i8PtrTy, T::FKeyPtrTy, T::FKeyPtrTy, T::i32Ty, T::i8Ty, T::Arr_2_i8Ty, T::Arr_2_TriggerPtrTy, T::Arr_1_sColMapTy }, false);
    T::ExprList_itemTy->setBody({ T::ExprPtrTy, T::i8PtrTy, T::i8Ty, T::i8Ty, T::anon1Ty }, false);
    T::ExprListTy->setBody({ T::i32Ty, T::Arr_1_ExprList_itemTy }, false);
    T::anon1Ty->setBody({ T::i32Ty }, false);
    T::TriggerTy->setBody({ T::i8PtrTy, T::i8PtrTy, T::i8Ty, T::i8Ty, T::ExprPtrTy, T::IdListPtrTy, T::SchemaPtrTy, T::SchemaPtrTy, T::TriggerStepPtrTy, T::TriggerPtrTy }, false);
    T::TriggerStepTy->setBody({ T::i8Ty, T::i8Ty, T::TriggerPtrTy, T::SelectPtrTy, T::i8PtrTy, T::ExprPtrTy, T::ExprListPtrTy, T::IdListPtrTy, T::UpsertPtrTy, T::i8PtrTy, T::TriggerStepPtrTy, T::TriggerStepPtrTy }, false);
    T::UpsertTy->setBody({ T::ExprListPtrTy, T::ExprPtrTy, T::ExprListPtrTy, T::ExprPtrTy, T::IndexPtrTy, T::SrcListPtrTy, T::i32Ty, T::i32Ty, T::i32Ty }, false);
    T::sqlite3InitInfoTy->setBody({ T::i32Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8PtrPtrTy }, false);
    T::ParseTy->setBody({ T::sqlite3PtrTy, T::i8PtrTy, T::VdbePtrTy, T::i32Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32PtrTy, T::ExprListPtrTy, T::TokenTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::TableLockPtrTy, T::AutoincInfoPtrTy, T::ParsePtrTy, T::TablePtrTy, T::ParsePtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::Arr_8_i32Ty, T::TokenTy, T::TokenTy, T::i16Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i32Ty, T::i32Ty, T::i32Ty, T::i32PtrTy, T::VdbePtrTy, T::i8PtrTy, T::TablePtrTy, T::IndexPtrTy, T::TriggerPtrTy, T::i8PtrTy, T::TokenTy, T::TablePtrPtrTy, T::TablePtrTy, T::TriggerPrgPtrTy, T::WithPtrTy, T::WithPtrTy, T::RenameTokenPtrTy }, false);
    T::AutoincInfoTy->setBody({ T::AutoincInfoPtrTy, T::TablePtrTy, T::i32Ty, T::i32Ty }, false);
    T::TokenTy->setBody({ T::i8PtrTy, T::i32Ty }, false);
    T::TriggerPrgTy->setBody({ T::TriggerPtrTy, T::TriggerPrgPtrTy, T::SubProgramPtrTy, T::i32Ty, T::Arr_2_i32Ty }, false);
    T::anon6Ty->setBody({ T::doubleTy }, false);
    T::LookasideTy->setBody({ T::i32Ty, T::i16Ty, T::i16Ty, T::i8Ty, T::i32Ty, T::Arr_3_i32Ty, T::LookasideSlotPtrTy, T::LookasideSlotPtrTy, T::LookasideSlotPtrTy, T::LookasideSlotPtrTy, T::i8PtrTy, T::i8PtrTy, T::i8PtrTy }, false);
    T::LookasideSlotTy->setBody({ T::LookasideSlotPtrTy }, false);
    T::VTableTy->setBody({ T::sqlite3PtrTy, T::ModulePtrTy, T::sqlite3_vtabPtrTy, T::i32Ty, T::i8Ty, T::i8Ty, T::i32Ty, T::VTablePtrTy }, false);
    T::ModuleTy->setBody({ T::sqlite3_modulePtrTy, T::i8PtrTy, T::i32Ty, T::i8PtrTy, T::Void_Of_i8PtrPtrTy, T::TablePtrTy }, false);
    T::sqlite3_moduleTy->setBody({ T::i32Ty, T::i32_Of_sqlite3Ptr_i8Ptr_i32_i8PtrPtr_sqlite3_vtabPtrPtr_i8PtrPtrPtrTy, T::i32_Of_sqlite3Ptr_i8Ptr_i32_i8PtrPtr_sqlite3_vtabPtrPtr_i8PtrPtrPtrTy, T::i32_Of_sqlite3_vtabPtr_sqlite3_index_infoPtrPtrTy, T::i32_Of_sqlite3_vtabPtrPtrTy, T::i32_Of_sqlite3_vtabPtrPtrTy, T::i32_Of_sqlite3_vtabPtr_sqlite3_vtab_cursorPtrPtrPtrTy, T::i32_Of_sqlite3_vtab_cursorPtrPtrTy, T::i32_Of_sqlite3_vtab_cursorPtr_i32_i8Ptr_i32_sqlite3_valuePtrPtrPtrTy, T::i32_Of_sqlite3_vtab_cursorPtrPtrTy, T::i32_Of_sqlite3_vtab_cursorPtrPtrTy, T::i32_Of_sqlite3_vtab_cursorPtr_sqlite3_contextPtr_i32PtrTy, T::i32_Of_sqlite3_vtab_cursorPtr_i64PtrPtrTy, T::i32_Of_sqlite3_vtabPtr_i32_sqlite3_valuePtrPtr_i64PtrPtrTy, T::i32_Of_sqlite3_vtabPtrPtrTy, T::i32_Of_sqlite3_vtabPtrPtrTy, T::i32_Of_sqlite3_vtabPtrPtrTy, T::i32_Of_sqlite3_vtabPtrPtrTy, T::i32_Of_sqlite3_vtabPtr_i32_i8Ptr_PxFunctionPtr_i8PtrPtrPtrTy, T::i32_Of_sqlite3_vtabPtr_i8PtrPtrTy, T::i32_Of_sqlite3_vtabPtr_i32PtrTy, T::i32_Of_sqlite3_vtabPtr_i32PtrTy, T::i32_Of_sqlite3_vtabPtr_i32PtrTy, T::i32_Of_i8PtrPtrTy }, false);
    T::sqlite3_index_infoTy->setBody({ T::i32Ty, T::sqlite3_index_constraintPtrTy, T::i32Ty, T::sqlite3_index_orderbyPtrTy, T::sqlite3_index_constraint_usagePtrTy, T::i32Ty, T::i8PtrTy, T::i32Ty, T::i32Ty, T::doubleTy, T::i64Ty, T::i32Ty, T::i64Ty }, false);
    T::sqlite3_index_constraintTy->setBody({ T::i32Ty, T::i8Ty, T::i8Ty, T::i32Ty }, false);
    T::sqlite3_index_orderbyTy->setBody({ T::i32Ty, T::i8Ty }, false);
    T::sqlite3_index_constraint_usageTy->setBody({ T::i32Ty, T::i8Ty }, false);
    T::sqlite3_vtab_cursorTy->setBody({ T::sqlite3_vtabPtrTy }, false);
    T::sqlite3_vtabTy->setBody({ T::sqlite3_modulePtrTy, T::i32Ty, T::i8PtrTy }, false);
    T::HashTy->setBody({ T::i32Ty, T::i32Ty, T::HashElemPtrTy, T::_htPtrTy }, false);
    T::HashElemTy->setBody({ T::HashElemPtrTy, T::HashElemPtrTy, T::i8PtrTy, T::i8PtrTy }, false);
    T::_htTy->setBody({ T::i32Ty, T::HashElemPtrTy }, false);
    T::BusyHandlerTy->setBody({ T::i32_Of_i8Ptr_i32PtrTy, T::i8PtrTy, T::i32Ty, T::i8Ty }, false);
    T::SavepointTy->setBody({ T::i8PtrTy, T::i64Ty, T::i64Ty, T::SavepointPtrTy }, false);
    T::UnpackedRecordTy->setBody({ T::KeyInfoPtrTy, T::sqlite3_valuePtrTy, T::i16Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty, T::i8Ty }, false);
    T::BtreePayloadTy->setBody({ T::i8PtrTy, T::i64Ty, T::i8PtrTy, T::sqlite3_valuePtrTy, T::i16Ty, T::i32Ty, T::i32Ty }, false);
    T::InitDataTy->setBody({ T::sqlite3PtrTy, T::i8PtrPtrTy, T::i32Ty, T::i32Ty, T::i32Ty, T::i32Ty }, false);
}
