#pragma once

#define INCOMPLETE_LOWERING_USED 101
#define OUT_OF_MEMORY 102
#define SQLITE_BRIDGE_FAILURE 103
#define UNDEFINED_USE_DEFAULT_IMPL 104
#define UNSUPPORTED_OPCODE 105
#define UNSUPPORTED_ADVANCER 106
#define ILLEGAL_LOWERING_USED 107
#define UNIMPLEMENTED_LOWERING_USED 108
#define ILLEGAL_TYPE_USED 109
